import type { Command, SearchEngine } from './types';

/**
 * Sites that expose no stable public search endpoint (login-walled apps,
 * workspace-scoped tools) degrade to a Google `site:` search so that arguments
 * are never silently dropped. Bare invocation still lands on the app itself.
 */
function siteSearch(host: string): string {
  return `https://www.google.com/search?q=site%3A${host}+{q}`;
}

/**
 * Meta commands carry a *relative* path so that `resolve()` stays pure and
 * chrome-free. The dispatch page (go.html) turns it into an absolute URL with
 * `chrome.runtime.getURL()` before navigating.
 */
const OPTIONS_PAGE = 'options.html';

export const BUILTIN_COMMANDS: Command[] = [
  // ---------------------------------------------------------------- ai ----
  {
    keys: ['c', 'claude'],
    name: 'Claude',
    description: 'Ask Claude, or open a new chat.',
    url: 'https://claude.ai/new',
    handler: 'ai',
    provider: 'claude',
    category: 'ai',
    builtin: true,
    example: 'c explain monads in one paragraph',
  },
  {
    keys: ['gpt', 'chatgpt'],
    name: 'ChatGPT',
    description: 'Ask ChatGPT, or open a new chat.',
    url: 'https://chatgpt.com/',
    handler: 'ai',
    provider: 'chatgpt',
    category: 'ai',
    builtin: true,
    example: 'gpt regex for iso dates',
  },
  {
    keys: ['gem', 'gemini'],
    name: 'Gemini',
    description: 'Ask Google Gemini, or open a new chat.',
    url: 'https://gemini.google.com/app',
    handler: 'ai',
    provider: 'gemini',
    category: 'ai',
    builtin: true,
    example: 'gem summarize the CAP theorem',
  },
  {
    keys: ['cc'],
    name: 'Claude Code',
    description: 'Claude Code on the web.',
    url: 'https://claude.ai/code',
    handler: 'ai',
    provider: 'claudecode',
    category: 'ai',
    builtin: true,
    example: 'cc add a retry to the fetch helper',
  },
  {
    keys: ['?'],
    name: 'Default AI',
    description: 'Send the prompt to whichever AI is set as default in settings.',
    url: 'https://claude.ai/new',
    handler: 'ai',
    category: 'ai',
    builtin: true,
    example: '? what is a merkle tree',
  },
  {
    keys: ['grok'],
    name: 'Grok',
    description: 'Ask Grok.',
    url: 'https://grok.com/',
    searchUrl: 'https://grok.com/?q={q}',
    category: 'ai',
    builtin: true,
    example: 'grok latest on the falcon launch',
  },
  {
    // Consumer Copilot has no supported search route: every `?q=` form
    // (including Microsoft's own bing.com/search?showconv=1 entry point) 302s
    // to the bare home page and drops the prompt. Open the app rather than a
    // guessed URL.
    keys: ['copilot', 'msai'],
    name: 'Microsoft Copilot',
    description: 'Open Microsoft Copilot; arguments search the web.',
    url: 'https://copilot.microsoft.com/',
    // The app is a chat SPA with nothing indexed, so a site: search would be as
    // empty as dropping the words: they go to a plain search instead.
    handler: 'unindexed',
    category: 'ai',
    builtin: true,
    example: 'copilot -> copilot.microsoft.com',
  },
  {
    keys: ['hf', 'huggingface'],
    name: 'Hugging Face',
    description: 'Search models, datasets and spaces.',
    url: 'https://huggingface.co/',
    searchUrl: 'https://huggingface.co/search/full-text?q={q}',
    category: 'ai',
    builtin: true,
    example: 'hf whisper large',
  },

  // ------------------------------------------------------------ google ----
  {
    keys: ['gmail', 'gm', 'mail'],
    name: 'Gmail',
    description: 'Open Gmail or search your mail.',
    url: 'https://mail.google.com/mail/u/0/',
    handler: 'gmail',
    category: 'google',
    builtin: true,
    example: 'gmail from:advisor has:attachment',
  },
  {
    keys: ['gdrive', 'gd', 'drive'],
    name: 'Google Drive',
    description: 'Open Drive or search your files.',
    url: 'https://drive.google.com/drive/u/0/',
    handler: 'gdrive',
    category: 'google',
    builtin: true,
    example: 'gd cs180 syllabus',
  },
  {
    keys: ['gcal', 'cal', 'calendar'],
    name: 'Google Calendar',
    description: 'Open Calendar or search your events.',
    url: 'https://calendar.google.com/calendar/u/0/r',
    handler: 'gcal',
    category: 'google',
    builtin: true,
    example: 'gcal office hours',
  },
  {
    keys: ['doc', 'docs'],
    name: 'Google Docs',
    description: 'Open Docs or search your documents.',
    url: 'https://docs.google.com/document/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'doc lab report',
  },
  {
    keys: ['sheet', 'sheets'],
    name: 'Google Sheets',
    description: 'Open Sheets or search your spreadsheets.',
    url: 'https://docs.google.com/spreadsheets/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'sheet budget 2026',
  },
  {
    keys: ['slide', 'slides'],
    name: 'Google Slides',
    description: 'Open Slides or search your decks.',
    url: 'https://docs.google.com/presentation/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'slide senior design',
  },
  {
    keys: ['gform', 'forms'],
    name: 'Google Forms',
    description: 'Open Forms or search your forms.',
    url: 'https://docs.google.com/forms/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'gform club signup',
  },
  {
    keys: ['gkeep', 'keep'],
    name: 'Google Keep',
    description: 'Open Keep or search your notes.',
    url: 'https://keep.google.com/',
    searchUrl: 'https://keep.google.com/#search/text={q}',
    category: 'google',
    builtin: true,
    example: 'gkeep groceries',
  },
  {
    keys: ['gphotos', 'photos'],
    name: 'Google Photos',
    description: 'Open Photos or search your library.',
    url: 'https://photos.google.com/',
    searchUrl: 'https://photos.google.com/search/{q}',
    category: 'google',
    builtin: true,
    example: 'gphotos graduation',
  },
  {
    keys: ['gmeet', 'meet'],
    name: 'Google Meet',
    description: 'Start Meet, or join a meeting by code.',
    url: 'https://meet.google.com/',
    searchUrl: 'https://meet.google.com/{q}',
    handler: 'meet',
    category: 'google',
    builtin: true,
    example: 'gmeet abc-defg-hij',
  },
  {
    keys: ['gcontacts', 'contacts'],
    name: 'Google Contacts',
    description: 'Open Contacts or search people.',
    url: 'https://contacts.google.com/',
    searchUrl: 'https://contacts.google.com/search/{q}',
    category: 'google',
    builtin: true,
    example: 'gcontacts jordan',
  },
  {
    keys: ['gtrans', 'translate', 'tr'],
    name: 'Google Translate',
    description: 'Translate text into English (auto-detect source).',
    url: 'https://translate.google.com/',
    searchUrl: 'https://translate.google.com/?sl=auto&tl=en&op=translate&text={q}',
    category: 'google',
    builtin: true,
    example: 'tr wo ist der bahnhof',
  },
  {
    keys: ['gmaps', 'maps', 'map'],
    name: 'Google Maps',
    description: 'Search Google Maps.',
    url: 'https://www.google.com/maps',
    searchUrl: 'https://www.google.com/maps/search/{q}',
    category: 'google',
    builtin: true,
    example: 'maps coffee near me',
  },
  {
    keys: ['gscholar', 'sch', 'scholar'],
    name: 'Google Scholar',
    description: 'Search academic papers.',
    url: 'https://scholar.google.com/',
    searchUrl: 'https://scholar.google.com/scholar?q={q}',
    category: 'google',
    builtin: true,
    example: 'sch attention is all you need',
  },
  {
    keys: ['gnews', 'news'],
    name: 'Google News',
    description: 'Search the news.',
    url: 'https://news.google.com/',
    searchUrl: 'https://news.google.com/search?q={q}',
    category: 'google',
    builtin: true,
    example: 'news semiconductor tariffs',
  },
  {
    keys: ['gimg', 'img', 'images'],
    name: 'Google Images',
    description: 'Google image search.',
    url: 'https://images.google.com/',
    searchUrl: 'https://www.google.com/search?tbm=isch&q={q}',
    category: 'google',
    builtin: true,
    example: 'img purdue bell tower',
  },
  {
    keys: ['gvid', 'videos'],
    name: 'Google Video',
    description: 'Google video search.',
    url: 'https://www.google.com/search?tbm=vid',
    searchUrl: 'https://www.google.com/search?tbm=vid&q={q}',
    category: 'google',
    builtin: true,
    example: 'gvid rust lifetimes talk',
  },
  {
    keys: ['gbooks', 'books'],
    name: 'Google Books',
    description: 'Search books.',
    url: 'https://books.google.com/',
    searchUrl: 'https://www.google.com/search?tbm=bks&q={q}',
    category: 'google',
    builtin: true,
    example: 'gbooks godel escher bach',
  },
  {
    keys: ['gflights', 'flights'],
    name: 'Google Flights',
    description: 'Search flights.',
    url: 'https://www.google.com/travel/flights',
    searchUrl: 'https://www.google.com/travel/flights?q={q}',
    category: 'google',
    builtin: true,
    example: 'gflights ind to sfo friday',
  },
  {
    keys: ['gtrends', 'trends'],
    name: 'Google Trends',
    description: 'Explore search interest over time.',
    url: 'https://trends.google.com/trends/',
    searchUrl: 'https://trends.google.com/trends/explore?q={q}',
    category: 'google',
    builtin: true,
    example: 'gtrends electric vehicles',
  },
  {
    keys: ['gplay', 'play'],
    name: 'Google Play',
    description: 'Search the Play Store.',
    url: 'https://play.google.com/store',
    searchUrl: 'https://play.google.com/store/search?q={q}',
    category: 'google',
    builtin: true,
    example: 'gplay duolingo',
  },
  {
    keys: ['gfonts', 'fonts'],
    name: 'Google Fonts',
    description: 'Browse and search fonts.',
    url: 'https://fonts.google.com/',
    searchUrl: 'https://fonts.google.com/?query={q}',
    category: 'google',
    builtin: true,
    example: 'gfonts inter',
  },

  // --------------------------------------------------------- microsoft ----
  {
    keys: ['outlook', 'ol', 'o365mail', 'pmail', 'purduemail'],
    name: 'Outlook',
    description: 'Open Outlook or Purdue webmail, or search your mail.',
    url: 'https://outlook.office.com/mail/',
    handler: 'outlook',
    category: 'microsoft',
    builtin: true,
    example: 'ol invoice from:finance',
  },
  {
    keys: ['onedrive', 'od'],
    name: 'OneDrive',
    description: 'Open OneDrive or search your files.',
    url: 'https://m365.cloud.microsoft/onedrive',
    handler: 'onedrive',
    category: 'microsoft',
    builtin: true,
    example: 'od q3 report',
  },
  {
    keys: ['teams', 'tm', 'msteams'],
    name: 'Microsoft Teams',
    description: 'Open Teams or search messages.',
    url: 'https://teams.microsoft.com/',
    handler: 'teams',
    category: 'microsoft',
    builtin: true,
    example: 'teams standup notes',
  },
  {
    keys: ['office', 'm365'],
    name: 'Microsoft 365',
    description: 'The Microsoft 365 portal, or search your content.',
    // The m365.cloud.microsoft root serves an empty 79-byte stub; `/apps` is
    // the real portal entry point.
    url: 'https://m365.cloud.microsoft/apps',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'office expense template',
  },
  {
    keys: ['excel', 'xl'],
    name: 'Excel',
    description: 'Excel for the web, or search your workbooks.',
    url: 'https://m365.cloud.microsoft/launch/excel',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'excel budget',
  },
  {
    keys: ['word', 'msword'],
    name: 'Word',
    description: 'Word for the web, or search your documents.',
    url: 'https://m365.cloud.microsoft/launch/word',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'word cover letter',
  },
  {
    keys: ['ppt', 'powerpoint'],
    name: 'PowerPoint',
    description: 'PowerPoint for the web, or search your decks.',
    url: 'https://m365.cloud.microsoft/launch/powerpoint',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'ppt kickoff deck',
  },
  {
    keys: ['onenote'],
    name: 'OneNote',
    description: 'OneNote notebooks, or search your content.',
    url: 'https://onenote.cloud.microsoft/',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'onenote lecture notes',
  },
  {
    keys: ['sharepoint', 'sp'],
    name: 'SharePoint',
    description: 'SharePoint start page, or search your sites.',
    url: 'https://m365.cloud.microsoft/launch/sharepoint',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'sharepoint team site',
  },
  {
    keys: ['azure', 'az'],
    name: 'Azure Portal',
    description: 'Azure portal; arguments search Microsoft Learn.',
    url: 'https://portal.azure.com/',
    searchUrl: 'https://learn.microsoft.com/en-us/search/?terms={q}',
    category: 'microsoft',
    builtin: true,
    example: 'az blob storage lifecycle',
  },
  {
    keys: ['mslearn', 'learn'],
    name: 'Microsoft Learn',
    description: 'Microsoft technical documentation.',
    url: 'https://learn.microsoft.com/',
    searchUrl: 'https://learn.microsoft.com/en-us/search/?terms={q}',
    category: 'microsoft',
    builtin: true,
    example: 'mslearn graph api permissions',
  },

  // ------------------------------------------------------------ purdue ----
  {
    keys: ['bs', 'brightspace', 'd2l'],
    name: 'Purdue Brightspace',
    description: 'Purdue course pages in Brightspace.',
    url: 'https://purdue.brightspace.com/d2l/home',
    handler: 'brightspace',
    category: 'purdue',
    builtin: true,
    example: 'bs cs251',
  },
  {
    keys: ['gs', 'gradescope'],
    name: 'Gradescope',
    description: 'Gradescope courses and assignments.',
    url: 'https://www.gradescope.com/',
    handler: 'gradescope',
    category: 'purdue',
    builtin: true,
    example: 'gs -> gradescope.com',
  },
  {
    // Gradescope's own login page; "School Credentials" is the Purdue SAML SSO
    // path. Purdue's former idp/gradescope1 entry point no longer exists.
    keys: ['gss', 'gradescopesso'],
    name: 'Gradescope (Purdue login)',
    description: 'Sign in to Gradescope with Purdue school credentials.',
    url: 'https://www.gradescope.com/login',
    searchUrl: siteSearch('gradescope.com'),
    category: 'purdue',
    builtin: true,
    example: 'gss -> Gradescope login (School Credentials)',
  },
  {
    keys: ['boilerlink', 'blink', 'bl2'],
    name: 'BoilerLink',
    description: 'Purdue student organizations and events.',
    url: 'https://boilerlink.purdue.edu/',
    // Campus Labs Engage is a SPA with nothing indexed by Google, so this uses
    // its own organization directory search instead of the usual site: fallback.
    searchUrl: 'https://boilerlink.purdue.edu/organizations?query={q}',
    category: 'purdue',
    builtin: true,
    example: 'boilerlink hackers club',
  },
  {
    keys: ['mypurdue'],
    name: 'myPurdue',
    description: 'Registration, grades, bills and holds.',
    // Login-walled portal: nothing behind it is indexed, but the registrar and
    // student-services pages that explain it are, so arguments search purdue.edu.
    url: 'https://wl.mypurdue.purdue.edu/',
    searchUrl: siteSearch('purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'mypurdue -> mypurdue.purdue.edu',
  },
  {
    keys: ['purdue', 'pu'],
    name: 'Purdue University',
    description: 'purdue.edu, or search the Purdue site.',
    url: 'https://www.purdue.edu/',
    searchUrl: siteSearch('purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'purdue academic integrity policy',
  },
  {
    keys: ['boilerconnect', 'bcon'],
    name: 'BoilerConnect',
    description: 'Advising appointments and student success.',
    url: 'https://purdue.campus.eab.com/',
    searchUrl: siteSearch('purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'boilerconnect -> advising appointments',
  },
  {
    keys: ['purduecal', 'pcal', 'acal'],
    name: 'Purdue Academic Calendar',
    description: 'Registrar calendars: term dates, breaks, finals.',
    url: 'https://www.purdue.edu/registrar/calendars/',
    searchUrl: siteSearch('purdue.edu/registrar'),
    category: 'purdue',
    builtin: true,
    example: 'purduecal spring finals week',
  },
  {
    keys: ['purduedining', 'dining', 'pdining'],
    name: 'Purdue Dining',
    description: 'Dining court menus and hours.',
    url: 'https://dining.purdue.edu/',
    searchUrl: siteSearch('dining.purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'dining wiley menu',
  },
  {
    keys: ['courseinsights', 'ci'],
    name: 'Purdue Course Insights',
    description: 'Course grade distributions; arguments search the web.',
    // Login-walled SPA: a site: fallback would send arguments nowhere useful, so
    // they go to a plain search. A bare invocation opens the app.
    url: 'https://sswis.mypurdue.purdue.edu/CourseInsights/',
    handler: 'unindexed',
    category: 'purdue',
    builtin: true,
    example: 'ci -> Course Insights',
  },
  {
    keys: ['catalog', 'pcat', 'courses'],
    name: 'Purdue Course Catalog',
    description: 'Official course descriptions and requirements.',
    url: 'https://catalog.purdue.edu/',
    searchUrl: siteSearch('catalog.purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'catalog ma 26100',
  },
  {
    keys: ['purduelib', 'plib', 'libraries'],
    name: 'Purdue Libraries',
    description: 'Library hours, databases and study rooms.',
    url: 'https://www.lib.purdue.edu/',
    searchUrl: siteSearch('lib.purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'purduelib ieee xplore',
  },
  {
    keys: ['recwell', 'corec'],
    name: 'Purdue RecWell',
    description: 'CoRec hours, classes and intramurals.',
    url: 'https://www.purdue.edu/recwell/',
    searchUrl: siteSearch('purdue.edu/recwell'),
    category: 'purdue',
    builtin: true,
    example: 'recwell pool hours',
  },
  {
    keys: ['citybus', 'bus'],
    name: 'CityBus',
    description: 'Greater Lafayette CityBus routes and tracker.',
    url: 'https://www.in.gov/citybuslafayette/',
    searchUrl: siteSearch('in.gov/citybuslafayette'),
    category: 'purdue',
    builtin: true,
    example: 'citybus route 4',
  },
  {
    keys: ['purduesports', 'boilers'],
    name: 'Purdue Athletics',
    description: 'Schedules, scores and tickets.',
    url: 'https://purduesports.com/',
    searchUrl: siteSearch('purduesports.com'),
    category: 'purdue',
    builtin: true,
    example: 'boilers basketball schedule',
  },
  {
    keys: ['piazza'],
    name: 'Piazza',
    description: 'Course Q&A boards.',
    url: 'https://piazza.com/',
    searchUrl: siteSearch('piazza.com'),
    category: 'purdue',
    builtin: true,
    example: 'piazza -> piazza.com',
  },

  // --------------------------------------------------------------- dev ----
  {
    keys: ['gh', 'github'],
    name: 'GitHub',
    description: 'Jump to a repo, a user, or search GitHub.',
    url: 'https://github.com/',
    handler: 'github',
    category: 'dev',
    builtin: true,
    example: 'gh facebook/react -> github.com/facebook/react',
  },
  {
    keys: ['pr', 'prs'],
    name: 'GitHub Pull Requests',
    description: 'Your pull requests, or the open PRs for a repo.',
    url: 'https://github.com/pulls',
    handler: 'githubPulls',
    category: 'dev',
    builtin: true,
    example: 'pr vitejs/vite -> open PRs for that repo',
  },
  {
    keys: ['iss', 'issues'],
    name: 'GitHub Issues',
    description: 'Your issues, or the issue list for a repo.',
    url: 'https://github.com/issues',
    handler: 'githubIssues',
    category: 'dev',
    builtin: true,
    example: 'iss microsoft/typescript',
  },
  {
    keys: ['gist', 'gists'],
    name: 'GitHub Gist',
    description: 'Your gists, or search public gists.',
    url: 'https://gist.github.com/',
    handler: 'githubGist',
    category: 'dev',
    builtin: true,
    example: 'gist bash prompt',
  },
  {
    keys: ['ghc', 'codesearch'],
    name: 'GitHub Code Search',
    description: 'Search code across GitHub.',
    url: 'https://github.com/search',
    searchUrl: 'https://github.com/search?type=code&q={q}',
    category: 'dev',
    builtin: true,
    example: 'ghc declarativeNetRequest addRules',
  },
  {
    keys: ['npm'],
    name: 'npm',
    description: 'Jump to a package page or search npm.',
    url: 'https://www.npmjs.com/',
    handler: 'npm',
    category: 'dev',
    builtin: true,
    example: 'npm zod -> npmjs.com/package/zod',
  },
  {
    keys: ['lh', 'localhost'],
    name: 'localhost',
    description: 'Open a local dev server. Bare invocation uses port 3000.',
    url: 'http://localhost:3000',
    handler: 'localhost',
    category: 'dev',
    builtin: true,
    example: 'lh 8080 -> http://localhost:8080',
  },
  {
    keys: ['so', 'stackoverflow'],
    name: 'Stack Overflow',
    description: 'Search Stack Overflow.',
    url: 'https://stackoverflow.com/',
    searchUrl: 'https://stackoverflow.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'so python asyncio gather exception',
  },
  {
    keys: ['mdn'],
    name: 'MDN Web Docs',
    description: 'Web platform documentation.',
    url: 'https://developer.mozilla.org/',
    searchUrl: 'https://developer.mozilla.org/en-US/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'mdn structuredClone',
  },
  {
    keys: ['caniuse', 'ciu'],
    name: 'Can I use',
    description: 'Browser support tables.',
    url: 'https://caniuse.com/',
    searchUrl: 'https://caniuse.com/?search={q}',
    category: 'dev',
    builtin: true,
    example: 'caniuse container queries',
  },
  {
    keys: ['lc', 'leetcode'],
    name: 'LeetCode',
    description: 'Search LeetCode problems.',
    url: 'https://leetcode.com/problemset/',
    searchUrl: 'https://leetcode.com/problemset/all/?search={q}',
    category: 'dev',
    builtin: true,
    example: 'lc two sum',
  },
  {
    keys: ['regex', 'regex101'],
    name: 'regex101',
    description: 'Test a regular expression.',
    url: 'https://regex101.com/',
    searchUrl: 'https://regex101.com/?regex={q}',
    category: 'dev',
    builtin: true,
    example: 'regex \\d{3}-\\d{4}',
  },
  {
    keys: ['pypi'],
    name: 'PyPI',
    description: 'Search Python packages.',
    url: 'https://pypi.org/',
    searchUrl: 'https://pypi.org/search/?q={q}',
    category: 'dev',
    builtin: true,
    example: 'pypi httpx',
  },
  {
    keys: ['pydocs', 'pydoc'],
    name: 'Python Docs',
    description: 'Search the Python 3 standard library docs.',
    url: 'https://docs.python.org/3/',
    searchUrl: 'https://docs.python.org/3/search.html?q={q}',
    category: 'dev',
    builtin: true,
    example: 'pydocs itertools groupby',
  },
  {
    keys: ['crates'],
    name: 'crates.io',
    description: 'Search Rust crates.',
    url: 'https://crates.io/',
    searchUrl: 'https://crates.io/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'crates serde',
  },
  {
    keys: ['docsrs'],
    name: 'docs.rs',
    description: 'Rust crate API documentation.',
    url: 'https://docs.rs/',
    searchUrl: 'https://docs.rs/releases/search?query={q}',
    category: 'dev',
    builtin: true,
    example: 'docsrs tokio',
  },
  {
    keys: ['golang', 'gopkg'],
    name: 'pkg.go.dev',
    description: 'Search Go packages.',
    url: 'https://pkg.go.dev/',
    searchUrl: 'https://pkg.go.dev/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'golang errgroup',
  },
  {
    keys: ['rubygems'],
    name: 'RubyGems',
    description: 'Search Ruby gems.',
    url: 'https://rubygems.org/',
    searchUrl: 'https://rubygems.org/search?query={q}',
    category: 'dev',
    builtin: true,
    example: 'rubygems rails',
  },
  {
    keys: ['packagist', 'composer'],
    name: 'Packagist',
    description: 'Search PHP packages.',
    url: 'https://packagist.org/',
    searchUrl: 'https://packagist.org/?query={q}',
    category: 'dev',
    builtin: true,
    example: 'packagist guzzle',
  },
  {
    keys: ['nuget'],
    name: 'NuGet',
    description: 'Search .NET packages.',
    url: 'https://www.nuget.org/',
    searchUrl: 'https://www.nuget.org/packages?q={q}',
    category: 'dev',
    builtin: true,
    example: 'nuget newtonsoft.json',
  },
  {
    keys: ['mvn', 'maven'],
    name: 'Maven Central',
    description: 'Search Java artifacts.',
    url: 'https://mvnrepository.com/',
    searchUrl: 'https://mvnrepository.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'mvn jackson databind',
  },
  {
    keys: ['dockerhub', 'docker'],
    name: 'Docker Hub',
    description: 'Search container images.',
    url: 'https://hub.docker.com/',
    searchUrl: 'https://hub.docker.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'docker postgres',
  },
  {
    keys: ['gitlab', 'gl'],
    name: 'GitLab',
    description: 'Search GitLab projects.',
    url: 'https://gitlab.com/',
    // gitlab.com/search requires auth and bounces signed-out users to sign-in;
    // /explore/projects is the public equivalent.
    searchUrl: 'https://gitlab.com/explore/projects?name={q}',
    category: 'dev',
    builtin: true,
    example: 'gitlab gitlab-runner',
  },
  {
    keys: ['bitbucket', 'bb'],
    name: 'Bitbucket',
    description: 'Bitbucket workspaces and repos.',
    url: 'https://bitbucket.org/',
    searchUrl: siteSearch('bitbucket.org'),
    category: 'dev',
    builtin: true,
    example: 'bitbucket -> bitbucket.org',
  },
  {
    keys: ['sourcegraph', 'sg'],
    name: 'Sourcegraph',
    description: 'Cross-repository code search.',
    url: 'https://sourcegraph.com/',
    searchUrl: 'https://sourcegraph.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'sg lang:go http.HandlerFunc',
  },
  {
    keys: ['devdocs', 'dd'],
    name: 'DevDocs',
    description: 'Unified API documentation browser.',
    url: 'https://devdocs.io/',
    searchUrl: 'https://devdocs.io/#q={q}',
    category: 'dev',
    builtin: true,
    example: 'dd array.prototype.flatmap',
  },
  {
    keys: ['ts', 'typescript'],
    name: 'TypeScript',
    description: 'TypeScript handbook and docs.',
    url: 'https://www.typescriptlang.org/',
    searchUrl: siteSearch('typescriptlang.org'),
    category: 'dev',
    builtin: true,
    example: 'ts satisfies operator',
  },
  {
    keys: ['react'],
    name: 'React',
    description: 'React documentation.',
    url: 'https://react.dev/',
    searchUrl: siteSearch('react.dev'),
    category: 'dev',
    builtin: true,
    example: 'react useSyncExternalStore',
  },
  {
    keys: ['node', 'nodedocs'],
    name: 'Node.js Docs',
    description: 'Node.js API documentation.',
    url: 'https://nodejs.org/api/',
    searchUrl: siteSearch('nodejs.org'),
    category: 'dev',
    builtin: true,
    example: 'node fs promises readFile',
  },
  {
    keys: ['bundlephobia', 'bphobia'],
    name: 'Bundlephobia',
    description: 'Size cost of an npm package.',
    url: 'https://bundlephobia.com/',
    searchUrl: 'https://bundlephobia.com/package/{q}',
    handler: 'pkg',
    category: 'dev',
    builtin: true,
    example: 'bundlephobia lodash',
  },
  {
    // Package pages intermittently 500 upstream (e.g. /react) while others load;
    // the URL shape is correct, so the command stays as-is.
    keys: ['npmtrends'],
    name: 'npm trends',
    description: 'Compare npm package downloads.',
    url: 'https://npmtrends.com/',
    searchUrl: 'https://npmtrends.com/{q}',
    handler: 'pkg',
    category: 'dev',
    builtin: true,
    example: 'npmtrends vite-vs-webpack',
  },
  {
    keys: ['codepen'],
    name: 'CodePen',
    description: 'Search pens.',
    url: 'https://codepen.io/',
    searchUrl: 'https://codepen.io/search/pens?q={q}',
    category: 'dev',
    builtin: true,
    example: 'codepen css grid gallery',
  },
  {
    keys: ['vscode', 'vsx'],
    name: 'VS Code',
    description: 'VS Code site; arguments search the extension marketplace.',
    url: 'https://code.visualstudio.com/',
    searchUrl: 'https://marketplace.visualstudio.com/search?target=VSCode&term={q}',
    category: 'dev',
    builtin: true,
    example: 'vsx eslint',
  },
  {
    keys: ['cws', 'chromestore'],
    name: 'Chrome Web Store',
    description: 'Search Chrome extensions.',
    url: 'https://chromewebstore.google.com/',
    searchUrl: 'https://chromewebstore.google.com/search/{q}',
    category: 'dev',
    builtin: true,
    example: 'cws ublock origin',
  },
  {
    keys: ['aws'],
    name: 'AWS',
    description: 'AWS console; arguments search AWS documentation.',
    url: 'https://console.aws.amazon.com/console/home',
    searchUrl: siteSearch('docs.aws.amazon.com'),
    category: 'dev',
    builtin: true,
    example: 'aws s3 presigned url',
  },
  {
    keys: ['gcp', 'gcloud'],
    name: 'Google Cloud',
    description: 'Cloud console; arguments search Google Cloud docs.',
    url: 'https://console.cloud.google.com/',
    searchUrl: siteSearch('cloud.google.com'),
    category: 'dev',
    builtin: true,
    example: 'gcp cloud run concurrency',
  },
  {
    keys: ['vercel'],
    name: 'Vercel',
    description: 'Vercel dashboard and docs.',
    url: 'https://vercel.com/dashboard',
    searchUrl: siteSearch('vercel.com'),
    category: 'dev',
    builtin: true,
    example: 'vercel edge middleware',
  },
  {
    keys: ['netlify'],
    name: 'Netlify',
    description: 'Netlify dashboard and docs.',
    url: 'https://app.netlify.com/',
    searchUrl: siteSearch('netlify.com'),
    category: 'dev',
    builtin: true,
    example: 'netlify redirects file',
  },
  {
    keys: ['cf', 'cloudflare'],
    name: 'Cloudflare',
    description: 'Cloudflare dashboard and docs.',
    url: 'https://dash.cloudflare.com/',
    searchUrl: siteSearch('developers.cloudflare.com'),
    category: 'dev',
    builtin: true,
    example: 'cf workers kv',
  },
  {
    keys: ['kaggle'],
    name: 'Kaggle',
    description: 'Search datasets, notebooks and competitions.',
    url: 'https://www.kaggle.com/',
    searchUrl: 'https://www.kaggle.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'kaggle titanic',
  },
  {
    keys: ['arxiv'],
    name: 'arXiv',
    description: 'Search preprints.',
    url: 'https://arxiv.org/',
    searchUrl: 'https://arxiv.org/search/?searchtype=all&query={q}',
    category: 'dev',
    builtin: true,
    example: 'arxiv speculative decoding',
  },

  // ------------------------------------------------------------ search ----
  {
    keys: ['g', 'google'],
    name: 'Google',
    description: 'Plain Google search.',
    url: 'https://www.google.com/',
    searchUrl: 'https://www.google.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'g best mechanical keyboard',
  },
  {
    keys: ['ddg', 'duckduckgo'],
    name: 'DuckDuckGo',
    description: 'Search DuckDuckGo.',
    url: 'https://duckduckgo.com/',
    searchUrl: 'https://duckduckgo.com/?q={q}',
    category: 'search',
    builtin: true,
    example: 'ddg privacy focused browsers',
  },
  {
    keys: ['bing', 'b'],
    name: 'Bing',
    description: 'Search Bing.',
    url: 'https://www.bing.com/',
    searchUrl: 'https://www.bing.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'bing weather chicago',
  },
  {
    keys: ['brave'],
    name: 'Brave Search',
    description: 'Search with Brave.',
    url: 'https://search.brave.com/',
    searchUrl: 'https://search.brave.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'brave rust vs zig',
  },
  {
    keys: ['kagi'],
    name: 'Kagi',
    description: 'Search with Kagi.',
    url: 'https://kagi.com/',
    searchUrl: 'https://kagi.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'kagi sqlite wal mode',
  },
  {
    keys: ['yt', 'youtube'],
    name: 'YouTube',
    description: 'Search YouTube, or jump to a channel with @handle.',
    url: 'https://www.youtube.com/',
    handler: 'youtube',
    category: 'search',
    builtin: true,
    example: 'yt lofi beats',
  },
  {
    keys: ['gsite', 'site'],
    name: 'Site search',
    description: 'Google a single site. First word is the domain.',
    url: 'https://www.google.com/',
    handler: 'gsite',
    category: 'search',
    builtin: true,
    example: 'gsite react.dev hooks -> google site:react.dev hooks',
  },
  {
    keys: ['wiki', 'w', 'wikipedia'],
    name: 'Wikipedia',
    description: 'Search English Wikipedia.',
    url: 'https://en.wikipedia.org/',
    searchUrl: 'https://en.wikipedia.org/w/index.php?search={q}',
    category: 'search',
    builtin: true,
    example: 'wiki halting problem',
  },
  {
    keys: ['amz', 'amazon'],
    name: 'Amazon',
    description: 'Search Amazon.',
    url: 'https://www.amazon.com/',
    searchUrl: 'https://www.amazon.com/s?k={q}',
    category: 'search',
    builtin: true,
    example: 'amz usb c hub',
  },
  {
    keys: ['ebay'],
    name: 'eBay',
    description: 'Search eBay listings.',
    url: 'https://www.ebay.com/',
    searchUrl: 'https://www.ebay.com/sch/i.html?_nkw={q}',
    category: 'search',
    builtin: true,
    example: 'ebay thinkpad x1',
  },
  {
    keys: ['hn', 'hackernews'],
    name: 'Hacker News',
    description: 'Search Hacker News via Algolia.',
    url: 'https://news.ycombinator.com/',
    searchUrl: 'https://hn.algolia.com/?q={q}',
    category: 'search',
    builtin: true,
    example: 'hn postgres full text search',
  },
  {
    keys: ['wa', 'wolfram'],
    name: 'WolframAlpha',
    description: 'Compute answers, units and math.',
    url: 'https://www.wolframalpha.com/',
    searchUrl: 'https://www.wolframalpha.com/input?i={q}',
    category: 'search',
    builtin: true,
    example: 'wa 42 miles in km',
  },
  {
    keys: ['def', 'dict', 'define'],
    name: 'Merriam-Webster',
    description: 'Look up a word.',
    url: 'https://www.merriam-webster.com/',
    searchUrl: 'https://www.merriam-webster.com/dictionary/{q}',
    handler: 'word',
    category: 'search',
    builtin: true,
    example: 'def defenestrate',
  },
  {
    keys: ['thes', 'thesaurus'],
    name: 'Thesaurus',
    description: 'Find synonyms.',
    url: 'https://www.thesaurus.com/',
    searchUrl: 'https://www.thesaurus.com/browse/{q}',
    handler: 'word',
    category: 'search',
    builtin: true,
    example: 'thes concise',
  },
  {
    keys: ['ud', 'urban'],
    name: 'Urban Dictionary',
    description: 'Slang definitions.',
    url: 'https://www.urbandictionary.com/',
    searchUrl: 'https://www.urbandictionary.com/define.php?term={q}',
    category: 'search',
    builtin: true,
    example: 'ud yeet',
  },
  {
    keys: ['weather', 'wx'],
    name: 'Weather',
    description: 'Weather for a place.',
    url: 'https://www.google.com/search?q=weather',
    searchUrl: 'https://www.google.com/search?q=weather+{q}',
    category: 'search',
    builtin: true,
    example: 'weather west lafayette',
  },
  {
    keys: ['stock', 'ticker'],
    name: 'Yahoo Finance',
    description: 'Quote for a ticker symbol.',
    url: 'https://finance.yahoo.com/',
    searchUrl: 'https://finance.yahoo.com/quote/{q}',
    handler: 'ticker',
    category: 'search',
    builtin: true,
    example: 'stock NVDA',
  },
  {
    keys: ['wayback', 'archive'],
    name: 'Wayback Machine',
    description: 'Latest archived snapshot of a URL.',
    url: 'https://web.archive.org/',
    searchUrl: 'https://web.archive.org/web/2/{q}',
    handler: 'wayback',
    category: 'search',
    builtin: true,
    example: 'wayback nytimes.com',
  },

  // ------------------------------------------------------------ social ----
  {
    keys: ['x', 'twitter', 'tw'],
    name: 'X',
    description: 'Search X, formerly Twitter.',
    url: 'https://x.com/',
    searchUrl: 'https://x.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'x from:sama',
  },
  {
    keys: ['li', 'linkedin'],
    name: 'LinkedIn',
    description: 'Search people, jobs and companies.',
    url: 'https://www.linkedin.com/feed/',
    searchUrl: 'https://www.linkedin.com/search/results/all/?keywords={q}',
    category: 'social',
    builtin: true,
    example: 'li software engineer intern',
  },
  {
    keys: ['rd', 'reddit', 'r'],
    name: 'Reddit',
    description: 'Jump to a subreddit or search Reddit.',
    url: 'https://www.reddit.com/',
    handler: 'reddit',
    category: 'social',
    builtin: true,
    example: 'rd r/purdue -> reddit.com/r/purdue',
  },
  {
    keys: ['ig', 'insta', 'instagram'],
    name: 'Instagram',
    description: 'Open a profile by username.',
    url: 'https://www.instagram.com/',
    searchUrl: 'https://www.instagram.com/{q}/',
    handler: 'instagram',
    category: 'social',
    builtin: true,
    example: 'ig nasa -> instagram.com/nasa',
  },
  {
    keys: ['fb', 'facebook'],
    name: 'Facebook',
    description: 'Search Facebook.',
    url: 'https://www.facebook.com/',
    searchUrl: 'https://www.facebook.com/search/top?q={q}',
    category: 'social',
    builtin: true,
    example: 'fb purdue engineering',
  },
  {
    keys: ['bsky', 'bluesky'],
    name: 'Bluesky',
    description: 'Search Bluesky.',
    url: 'https://bsky.app/',
    searchUrl: 'https://bsky.app/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'bsky atproto',
  },
  {
    keys: ['threads'],
    name: 'Threads',
    description: 'Search Threads.',
    url: 'https://www.threads.com/',
    searchUrl: 'https://www.threads.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'threads wwdc',
  },
  {
    keys: ['tt', 'tiktok'],
    name: 'TikTok',
    description: 'Search TikTok.',
    url: 'https://www.tiktok.com/',
    searchUrl: 'https://www.tiktok.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'tt study with me',
  },
  {
    keys: ['pin', 'pinterest'],
    name: 'Pinterest',
    description: 'Search pins.',
    url: 'https://www.pinterest.com/',
    searchUrl: 'https://www.pinterest.com/search/pins/?q={q}',
    category: 'social',
    builtin: true,
    example: 'pin desk setup',
  },
  {
    keys: ['quora'],
    name: 'Quora',
    description: 'Search questions and answers.',
    url: 'https://www.quora.com/',
    searchUrl: 'https://www.quora.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'quora how do jet engines work',
  },
  {
    keys: ['discord', 'dc'],
    name: 'Discord',
    description: 'Open Discord in the browser.',
    url: 'https://discord.com/channels/@me',
    searchUrl: siteSearch('discord.com'),
    category: 'social',
    builtin: true,
    example: 'discord -> discord.com',
  },
  {
    keys: ['slack', 'slk'],
    name: 'Slack',
    description: 'Open Slack in the browser.',
    url: 'https://app.slack.com/client',
    searchUrl: siteSearch('slack.com'),
    category: 'social',
    builtin: true,
    example: 'slack -> app.slack.com',
  },
  {
    keys: ['whatsapp', 'wapp'],
    name: 'WhatsApp',
    description: 'WhatsApp Web, or start a chat with a phone number.',
    url: 'https://web.whatsapp.com/',
    searchUrl: 'https://wa.me/{q}',
    handler: 'whatsapp',
    category: 'social',
    builtin: true,
    example: 'whatsapp 15551234567',
  },
  {
    keys: ['tg', 'telegram'],
    name: 'Telegram',
    description: 'Telegram Web, or open a @username.',
    url: 'https://web.telegram.org/',
    searchUrl: 'https://t.me/{q}',
    handler: 'telegram',
    category: 'social',
    builtin: true,
    example: 'tg durov',
  },

  // ------------------------------------------------------------- media ----
  {
    keys: ['spot', 'spotify'],
    name: 'Spotify',
    description: 'Search Spotify.',
    url: 'https://open.spotify.com/',
    searchUrl: 'https://open.spotify.com/search/{q}',
    category: 'media',
    builtin: true,
    example: 'spot bonobo',
  },
  {
    keys: ['ytm', 'ytmusic'],
    name: 'YouTube Music',
    description: 'Search YouTube Music.',
    url: 'https://music.youtube.com/',
    searchUrl: 'https://music.youtube.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'ytm radiohead',
  },
  {
    keys: ['sc', 'soundcloud'],
    name: 'SoundCloud',
    description: 'Search SoundCloud.',
    url: 'https://soundcloud.com/',
    searchUrl: 'https://soundcloud.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'sc dj sets',
  },
  {
    keys: ['bandcamp'],
    name: 'Bandcamp',
    description: 'Search artists and albums.',
    url: 'https://bandcamp.com/',
    searchUrl: 'https://bandcamp.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'bandcamp khruangbin',
  },
  {
    keys: ['genius'],
    name: 'Genius',
    description: 'Search song lyrics.',
    url: 'https://genius.com/',
    searchUrl: 'https://genius.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'genius pyramids',
  },
  {
    keys: ['nf', 'netflix'],
    name: 'Netflix',
    description: 'Search Netflix.',
    url: 'https://www.netflix.com/browse',
    searchUrl: 'https://www.netflix.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'nf arcane',
  },
  {
    keys: ['hulu'],
    name: 'Hulu',
    description: 'Search Hulu.',
    url: 'https://www.hulu.com/hub/home',
    searchUrl: 'https://www.hulu.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'hulu the bear',
  },
  {
    keys: ['primevideo', 'pv'],
    name: 'Prime Video',
    description: 'Open Prime Video.',
    url: 'https://www.primevideo.com/',
    searchUrl: siteSearch('primevideo.com'),
    category: 'media',
    builtin: true,
    example: 'primevideo -> primevideo.com',
  },
  {
    keys: ['disney', 'dplus'],
    name: 'Disney+',
    description: 'Open Disney+.',
    url: 'https://www.disneyplus.com/',
    searchUrl: siteSearch('disneyplus.com'),
    category: 'media',
    builtin: true,
    example: 'disney -> disneyplus.com',
  },
  {
    keys: ['twitch'],
    name: 'Twitch',
    description: 'Search Twitch channels and categories.',
    url: 'https://www.twitch.tv/',
    searchUrl: 'https://www.twitch.tv/search?term={q}',
    category: 'media',
    builtin: true,
    example: 'twitch speedrun',
  },
  {
    keys: ['imdb'],
    name: 'IMDb',
    description: 'Search films, shows and people.',
    url: 'https://www.imdb.com/',
    searchUrl: 'https://www.imdb.com/find/?q={q}',
    category: 'media',
    builtin: true,
    example: 'imdb dune part two',
  },
  {
    keys: ['rt', 'rottentomatoes'],
    name: 'Rotten Tomatoes',
    description: 'Search reviews and scores.',
    url: 'https://www.rottentomatoes.com/',
    searchUrl: 'https://www.rottentomatoes.com/search?search={q}',
    category: 'media',
    builtin: true,
    example: 'rt the batman',
  },
  {
    keys: ['lb', 'letterboxd'],
    name: 'Letterboxd',
    description: 'Search films on Letterboxd.',
    url: 'https://letterboxd.com/',
    searchUrl: 'https://letterboxd.com/search/{q}/',
    category: 'media',
    builtin: true,
    example: 'lb parasite',
  },
  {
    keys: ['gr', 'goodreads'],
    name: 'Goodreads',
    description: 'Search books and reviews.',
    url: 'https://www.goodreads.com/',
    searchUrl: 'https://www.goodreads.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'gr project hail mary',
  },
  {
    keys: ['mal', 'anime'],
    name: 'MyAnimeList',
    description: 'Search anime and manga.',
    url: 'https://myanimelist.net/',
    searchUrl: 'https://myanimelist.net/search/all?q={q}',
    category: 'media',
    builtin: true,
    example: 'mal frieren',
  },
  {
    keys: ['steam'],
    name: 'Steam',
    description: 'Search the Steam store.',
    url: 'https://store.steampowered.com/',
    searchUrl: 'https://store.steampowered.com/search/?term={q}',
    category: 'media',
    builtin: true,
    example: 'steam factorio',
  },
  {
    keys: ['vimeo'],
    name: 'Vimeo',
    description: 'Search Vimeo.',
    url: 'https://vimeo.com/',
    searchUrl: 'https://vimeo.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'vimeo short film',
  },

  // ------------------------------------------------------ productivity ----
  {
    // www.notion.so now 307s to the marketing homepage; app.notion.com is the
    // app shell. Notion exposes no URL-addressable workspace search, so
    // arguments degrade to the same site: search the other workspace tools use.
    keys: ['nt', 'notion'],
    name: 'Notion',
    description: 'Open Notion, or search public Notion pages.',
    url: 'https://app.notion.com/',
    searchUrl: siteSearch('notion.com'),
    category: 'productivity',
    builtin: true,
    example: 'nt meeting notes',
  },
  {
    keys: ['fig', 'figma'],
    name: 'Figma',
    description: 'Open your Figma files.',
    url: 'https://www.figma.com/files',
    searchUrl: siteSearch('figma.com'),
    category: 'productivity',
    builtin: true,
    example: 'fig -> figma.com/files',
  },
  {
    keys: ['lin', 'linear'],
    name: 'Linear',
    description: 'Open Linear.',
    url: 'https://linear.app/',
    searchUrl: siteSearch('linear.app'),
    category: 'productivity',
    builtin: true,
    example: 'lin -> linear.app',
  },
  {
    keys: ['jira'],
    name: 'Jira',
    description: 'Jira home and documentation.',
    url: 'https://www.atlassian.com/software/jira',
    searchUrl: siteSearch('atlassian.com'),
    category: 'productivity',
    builtin: true,
    example: 'jira jql order by',
  },
  {
    keys: ['asana'],
    name: 'Asana',
    description: 'Open Asana.',
    url: 'https://app.asana.com/',
    searchUrl: siteSearch('asana.com'),
    category: 'productivity',
    builtin: true,
    example: 'asana -> app.asana.com',
  },
  {
    keys: ['trello'],
    name: 'Trello',
    description: 'Search your Trello boards and cards.',
    url: 'https://trello.com/',
    searchUrl: 'https://trello.com/search?q={q}',
    category: 'productivity',
    builtin: true,
    example: 'trello sprint board',
  },
  {
    keys: ['canva'],
    name: 'Canva',
    description: 'Open Canva.',
    url: 'https://www.canva.com/',
    searchUrl: siteSearch('canva.com'),
    category: 'productivity',
    builtin: true,
    example: 'canva -> canva.com',
  },
  {
    // Arguments SEARCH. Quick-add lives on `tda` instead: a misread query
    // ("td bank near me") must not create a task, and every other command in
    // the registry is read-only.
    keys: ['todoist', 'td'],
    name: 'Todoist',
    description: 'Open Todoist, or search your tasks.',
    url: 'https://app.todoist.com/app/today',
    searchUrl: 'https://app.todoist.com/app/search/{q}',
    category: 'productivity',
    builtin: true,
    example: 'todoist email advisor',
  },
  {
    keys: ['tda', 'todoistadd'],
    name: 'Todoist quick add',
    description: 'Open the Todoist quick-add composer, prefilled.',
    url: 'https://app.todoist.com/add',
    searchUrl: 'https://app.todoist.com/add?content={q}',
    category: 'productivity',
    builtin: true,
    example: 'tda email advisor tomorrow',
  },
  {
    keys: ['1p', '1password'],
    name: '1Password',
    description: 'Open your 1Password vault.',
    url: 'https://my.1password.com/',
    searchUrl: siteSearch('1password.com'),
    category: 'productivity',
    builtin: true,
    example: '1p -> my.1password.com',
  },
  {
    keys: ['dbx', 'dropbox'],
    name: 'Dropbox',
    description: 'Open Dropbox.',
    url: 'https://www.dropbox.com/home',
    searchUrl: siteSearch('dropbox.com'),
    category: 'productivity',
    builtin: true,
    example: 'dbx -> dropbox.com/home',
  },
  {
    keys: ['airtable'],
    name: 'Airtable',
    description: 'Open Airtable.',
    url: 'https://www.airtable.com/',
    searchUrl: siteSearch('airtable.com'),
    category: 'productivity',
    builtin: true,
    example: 'airtable -> airtable.com',
  },
  {
    keys: ['miro'],
    name: 'Miro',
    description: 'Open your Miro boards.',
    url: 'https://miro.com/app/dashboard/',
    searchUrl: siteSearch('miro.com'),
    category: 'productivity',
    builtin: true,
    example: 'miro -> miro.com',
  },
  {
    keys: ['zoom'],
    name: 'Zoom',
    description: 'Open Zoom, or join a meeting by ID.',
    url: 'https://zoom.us/',
    searchUrl: 'https://zoom.us/j/{q}',
    handler: 'zoom',
    category: 'productivity',
    builtin: true,
    example: 'zoom 1234567890',
  },
  {
    keys: ['overleaf', 'tex'],
    name: 'Overleaf',
    description: 'LaTeX projects in the browser.',
    url: 'https://www.overleaf.com/project',
    searchUrl: siteSearch('overleaf.com'),
    category: 'productivity',
    builtin: true,
    example: 'overleaf bibliography styles',
  },
  {
    keys: ['desmos'],
    name: 'Desmos',
    description: 'Graphing calculator.',
    url: 'https://www.desmos.com/calculator',
    searchUrl: siteSearch('desmos.com'),
    category: 'productivity',
    builtin: true,
    example: 'desmos -> desmos.com/calculator',
  },
  {
    keys: ['ups'],
    name: 'UPS Tracking',
    description: 'Track a UPS shipment.',
    url: 'https://www.ups.com/track',
    searchUrl: 'https://www.ups.com/track?tracknum={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'ups 1Z999AA10123456784',
  },
  {
    keys: ['fedex'],
    name: 'FedEx Tracking',
    description: 'Track a FedEx shipment.',
    url: 'https://www.fedex.com/wtrk/track/',
    searchUrl: 'https://www.fedex.com/wtrk/track/?trknbr={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'fedex 123456789012',
  },
  {
    keys: ['usps'],
    name: 'USPS Tracking',
    description: 'Track a USPS shipment.',
    url: 'https://tools.usps.com/go/TrackConfirmAction',
    searchUrl: 'https://tools.usps.com/go/TrackConfirmAction?tLabels={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'usps 9400111899223197428490',
  },

  // -------------------------------------------------------------- meta ----
  {
    keys: ['bl', 'help', 'bunnylol'],
    name: 'BunnyLol help',
    description: 'Browse and search every shortcut.',
    url: `${OPTIONS_PAGE}#help`,
    handler: 'meta',
    category: 'meta',
    builtin: true,
    example: 'bl -> the full command list',
  },
  {
    keys: ['add', 'new'],
    name: 'New shortcut',
    description: 'Create a shortcut; arguments prefill the form.',
    url: `${OPTIONS_PAGE}#new`,
    handler: 'meta',
    category: 'meta',
    builtin: true,
    example: 'add tix https://example.com/search?q={q}',
  },
  {
    keys: ['set', 'settings', 'opts'],
    name: 'BunnyLol settings',
    description: 'Default engine, default AI, GitHub user, interception.',
    url: `${OPTIONS_PAGE}#settings`,
    handler: 'meta',
    category: 'meta',
    builtin: true,
    example: 'set -> the settings page',
  },
];

export const SEARCH_ENGINES: SearchEngine[] = [
  {
    id: 'google',
    label: 'Google',
    host: 'www.google.com',
    urlPrefixPattern: '^https://www\\.google\\.com/search\\?(?:[^#]*&)?q=',
  },
  {
    id: 'bing',
    label: 'Bing',
    host: 'www.bing.com',
    urlPrefixPattern: '^https://www\\.bing\\.com/search\\?(?:[^#]*&)?q=',
  },
  {
    id: 'duckduckgo',
    label: 'DuckDuckGo',
    host: 'duckduckgo.com',
    urlPrefixPattern: '^https://duckduckgo\\.com/\\?(?:[^#]*&)?q=',
  },
];
