import type { BuiltinCommand, Command, SearchEngine } from './types';

/**
 * Sites that expose no stable public search endpoint (login-walled apps,
 * workspace-scoped tools) degrade to a Google `site:` search so that arguments
 * are never silently dropped. Bare invocation still lands on the app itself.
 */
function siteSearch(host: string): string {
  return `https://www.google.com/search?q=site%3A${host}+{q}`;
}

/**
 * Meta commands carry a *relative* path so that `resolve()` stays pure and
 * chrome-free. The dispatch page (go.html) turns it into an absolute URL with
 * `chrome.runtime.getURL()` before navigating.
 */
const OPTIONS_PAGE = 'options.html';

export const BUILTIN_COMMANDS: BuiltinCommand[] = [
  // ---------------------------------------------------------------- ai ----
  {
    keys: ['c', 'claude'],
    name: 'Claude',
    description: 'Ask Claude, or open a new chat.',
    url: 'https://claude.ai/new',
    handler: 'ai',
    provider: 'claude',
    category: 'ai',
    builtin: true,
    example: 'c explain monads in one paragraph',
  },
  {
    keys: ['gpt', 'chatgpt'],
    name: 'ChatGPT',
    description: 'Ask ChatGPT, or open a new chat.',
    url: 'https://chatgpt.com/',
    handler: 'ai',
    provider: 'chatgpt',
    category: 'ai',
    builtin: true,
    example: 'gpt regex for iso dates',
  },
  {
    keys: ['gem', 'gemini'],
    name: 'Gemini',
    description: 'Ask Google Gemini, or open a new chat.',
    url: 'https://gemini.google.com/app',
    handler: 'ai',
    provider: 'gemini',
    category: 'ai',
    builtin: true,
    example: 'gem summarize the CAP theorem',
  },
  {
    keys: ['cc'],
    name: 'Claude Code',
    description: 'Claude Code on the web.',
    url: 'https://claude.ai/code',
    handler: 'ai',
    provider: 'claudecode',
    category: 'ai',
    builtin: true,
    example: 'cc add a retry to the fetch helper',
  },
  {
    keys: ['grok'],
    name: 'Grok',
    description: 'Ask Grok.',
    url: 'https://grok.com/',
    searchUrl: 'https://grok.com/?q={q}',
    category: 'ai',
    builtin: true,
    example: 'grok latest on the falcon launch',
  },

  // ------------------------------------------------------------ google ----
  {
    keys: ['gmail', 'gm', 'mail'],
    name: 'Gmail',
    description: 'Open Gmail or search your mail.',
    url: 'https://mail.google.com/mail/u/0/',
    handler: 'gmail',
    category: 'google',
    builtin: true,
    example: 'gmail from:advisor has:attachment',
  },
  {
    keys: ['gdrive', 'gd', 'drive'],
    name: 'Google Drive',
    description: 'Open Drive or search your files.',
    url: 'https://drive.google.com/drive/u/0/',
    handler: 'gdrive',
    category: 'google',
    builtin: true,
    example: 'gd cs180 syllabus',
  },
  {
    keys: ['gcal', 'cal', 'calendar'],
    name: 'Google Calendar',
    description: 'Open Calendar or search your events.',
    url: 'https://calendar.google.com/calendar/u/0/r',
    handler: 'gcal',
    category: 'google',
    builtin: true,
    example: 'gcal office hours',
  },
  {
    keys: ['doc', 'docs'],
    name: 'Google Docs',
    description: 'Open Docs or search your documents.',
    url: 'https://docs.google.com/document/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'doc lab report',
  },
  {
    keys: ['sheet', 'sheets'],
    name: 'Google Sheets',
    description: 'Open Sheets or search your spreadsheets.',
    url: 'https://docs.google.com/spreadsheets/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'sheet budget 2026',
  },
  {
    keys: ['slide', 'slides'],
    name: 'Google Slides',
    description: 'Open Slides or search your decks.',
    url: 'https://docs.google.com/presentation/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'slide senior design',
  },
  {
    keys: ['gform', 'forms'],
    name: 'Google Forms',
    description: 'Open Forms or search your forms.',
    url: 'https://docs.google.com/forms/u/0/',
    handler: 'googleApp',
    category: 'google',
    builtin: true,
    example: 'gform club signup',
  },
  {
    keys: ['gmeet', 'meet'],
    name: 'Google Meet',
    description: 'Start Meet, or join a meeting by code.',
    url: 'https://meet.google.com/',
    searchUrl: 'https://meet.google.com/{q}',
    handler: 'meet',
    category: 'google',
    builtin: true,
    example: 'gmeet abc-defg-hij',
  },
  {
    keys: ['gmaps', 'maps', 'map'],
    name: 'Google Maps',
    description: 'Search Google Maps.',
    url: 'https://www.google.com/maps',
    searchUrl: 'https://www.google.com/maps/search/{q}',
    category: 'google',
    builtin: true,
    example: 'maps coffee near me',
  },
  {
    keys: ['gfonts', 'fonts'],
    name: 'Google Fonts',
    description: 'Browse and search fonts.',
    url: 'https://fonts.google.com/',
    searchUrl: 'https://fonts.google.com/?query={q}',
    category: 'google',
    builtin: true,
    example: 'gfonts inter',
  },

  // --------------------------------------------------------- microsoft ----
  {
    keys: ['outlook', 'ol', 'o365mail', 'pmail', 'purduemail'],
    name: 'Outlook',
    description: 'Open Outlook or Purdue webmail, or search your mail.',
    url: 'https://outlook.office.com/mail/',
    handler: 'outlook',
    category: 'microsoft',
    builtin: true,
    example: 'ol invoice from:finance',
  },
  {
    keys: ['onedrive', 'od'],
    name: 'OneDrive',
    description: 'Open OneDrive or search your files.',
    url: 'https://m365.cloud.microsoft/onedrive',
    handler: 'onedrive',
    category: 'microsoft',
    builtin: true,
    example: 'od q3 report',
  },
  {
    keys: ['teams', 'tm', 'msteams'],
    name: 'Microsoft Teams',
    description: 'Open Teams or search messages.',
    url: 'https://teams.microsoft.com/',
    handler: 'teams',
    category: 'microsoft',
    builtin: true,
    example: 'teams standup notes',
  },
  {
    keys: ['office', 'm365'],
    name: 'Microsoft 365',
    description: 'The Microsoft 365 portal, or search your content.',
    // The m365.cloud.microsoft root serves an empty 79-byte stub; `/apps` is
    // the real portal entry point.
    url: 'https://m365.cloud.microsoft/apps',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'office expense template',
  },
  {
    keys: ['excel', 'xl'],
    name: 'Excel',
    description: 'Excel for the web, or search your workbooks.',
    url: 'https://m365.cloud.microsoft/launch/excel',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'excel budget',
  },
  {
    keys: ['word', 'msword'],
    name: 'Word',
    description: 'Word for the web, or search your documents.',
    url: 'https://m365.cloud.microsoft/launch/word',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'word cover letter',
  },
  {
    keys: ['ppt', 'powerpoint'],
    name: 'PowerPoint',
    description: 'PowerPoint for the web, or search your decks.',
    url: 'https://m365.cloud.microsoft/launch/powerpoint',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'ppt kickoff deck',
  },
  {
    keys: ['onenote'],
    name: 'OneNote',
    description: 'OneNote notebooks, or search your content.',
    url: 'https://onenote.cloud.microsoft/',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'onenote lecture notes',
  },

  // ------------------------------------------------------------ purdue ----
  // For these two rows `url` is the HOST, not just a destination. Brightspace
  // and Gradescope are multi-tenant products, so their handlers derive both the
  // deep link and the `site:` degrade from `url` and `searchUrl`: editing them
  // re-targets the command at another institution without touching any code.
  // Hosts that ARE a handler's identity stay literal in `handlers.ts`
  // instead: github.com, reddit.com, npmjs.com.
  {
    keys: ['bs', 'brightspace', 'd2l'],
    name: 'Purdue Brightspace',
    description: 'Purdue course pages in Brightspace.',
    url: 'https://purdue.brightspace.com/d2l/home',
    // The D2L host is login-walled, but Purdue's course and Brightspace pages on
    // purdue.edu are indexed: the same fallback `boilerconnect` already uses.
    searchUrl: siteSearch('purdue.edu'),
    handler: 'brightspace',
    category: 'purdue',
    builtin: true,
    example: 'bs cs251',
  },
  {
    keys: ['gs', 'gradescope'],
    name: 'Gradescope',
    description: 'Gradescope courses and assignments.',
    url: 'https://www.gradescope.com/',
    searchUrl: siteSearch('gradescope.com'),
    handler: 'gradescope',
    category: 'purdue',
    builtin: true,
    example: 'gs -> gradescope.com',
  },
  {
    keys: ['boilerlink', 'blink', 'bl2'],
    name: 'BoilerLink',
    description: 'Purdue student organizations and events.',
    url: 'https://boilerlink.purdue.edu/',
    // Campus Labs Engage is a SPA with nothing indexed by Google, so this uses
    // its own organization directory search instead of the usual site: fallback.
    searchUrl: 'https://boilerlink.purdue.edu/organizations?query={q}',
    category: 'purdue',
    builtin: true,
    example: 'boilerlink hackers club',
  },
  {
    keys: ['mypurdue'],
    name: 'myPurdue',
    description: 'Registration, grades, bills and holds.',
    // Login-walled portal: nothing behind it is indexed, but the registrar and
    // student-services pages that explain it are, so arguments search purdue.edu.
    url: 'https://wl.mypurdue.purdue.edu/',
    searchUrl: siteSearch('purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'mypurdue -> mypurdue.purdue.edu',
  },
  {
    keys: ['purduecal', 'pcal', 'acal'],
    name: 'Purdue Academic Calendar',
    description: 'Registrar calendars: term dates, breaks, finals.',
    url: 'https://www.purdue.edu/registrar/calendars/',
    searchUrl: siteSearch('purdue.edu/registrar'),
    category: 'purdue',
    builtin: true,
    example: 'purduecal spring finals week',
  },
  {
    keys: ['purduedining', 'dining', 'pdining'],
    name: 'Purdue Dining',
    description: 'Dining court menus and hours.',
    url: 'https://dining.purdue.edu/',
    searchUrl: siteSearch('dining.purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'dining wiley menu',
  },
  {
    keys: ['purduelib', 'plib', 'libraries'],
    name: 'Purdue Libraries',
    description: 'Library hours, databases and study rooms.',
    url: 'https://www.lib.purdue.edu/',
    searchUrl: siteSearch('lib.purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'purduelib ieee xplore',
  },
  {
    keys: ['recwell', 'corec'],
    name: 'Purdue RecWell',
    description: 'CoRec hours, classes and intramurals.',
    url: 'https://www.purdue.edu/recwell/',
    searchUrl: siteSearch('purdue.edu/recwell'),
    category: 'purdue',
    builtin: true,
    example: 'recwell pool hours',
  },

  // --------------------------------------------------------------- dev ----
  {
    keys: ['gh', 'github'],
    name: 'GitHub',
    description: 'Jump to a repo, a user, or search GitHub.',
    url: 'https://github.com/',
    handler: 'github',
    category: 'dev',
    builtin: true,
    example: 'gh facebook/react -> github.com/facebook/react',
  },
  {
    keys: ['pr', 'prs'],
    name: 'GitHub Pull Requests',
    description: 'Your pull requests, or the open PRs for a repo.',
    url: 'https://github.com/pulls',
    handler: 'githubPulls',
    category: 'dev',
    builtin: true,
    example: 'pr vitejs/vite -> open PRs for that repo',
  },
  {
    keys: ['iss', 'issues'],
    name: 'GitHub Issues',
    description: 'Your issues, or the issue list for a repo.',
    url: 'https://github.com/issues',
    handler: 'githubIssues',
    category: 'dev',
    builtin: true,
    example: 'iss microsoft/typescript',
  },
  {
    keys: ['gist', 'gists'],
    name: 'GitHub Gist',
    description: 'Your gists, or search public gists.',
    url: 'https://gist.github.com/',
    handler: 'githubGist',
    category: 'dev',
    builtin: true,
    example: 'gist bash prompt',
  },
  {
    keys: ['ghc', 'codesearch'],
    name: 'GitHub Code Search',
    description: 'Search code across GitHub.',
    url: 'https://github.com/search',
    searchUrl: 'https://github.com/search?type=code&q={q}',
    category: 'dev',
    builtin: true,
    example: 'ghc declarativeNetRequest addRules',
  },
  {
    keys: ['npm'],
    name: 'npm',
    description: 'Jump to a package page or search npm.',
    url: 'https://www.npmjs.com/',
    handler: 'npm',
    category: 'dev',
    builtin: true,
    example: 'npm zod -> npmjs.com/package/zod',
  },
  {
    keys: ['regex', 'regex101'],
    name: 'regex101',
    description: 'Test a regular expression.',
    url: 'https://regex101.com/',
    searchUrl: 'https://regex101.com/?regex={q}',
    category: 'dev',
    builtin: true,
    example: 'regex \\d{3}-\\d{4}',
  },
  {
    keys: ['cws', 'chromestore'],
    name: 'Chrome Web Store',
    description: 'Search Chrome extensions.',
    url: 'https://chromewebstore.google.com/',
    searchUrl: 'https://chromewebstore.google.com/search/{q}',
    category: 'dev',
    builtin: true,
    example: 'cws ublock origin',
  },
  {
    keys: ['aws'],
    name: 'AWS',
    description: 'AWS console.',
    url: 'https://console.aws.amazon.com/console/home',
    category: 'dev',
    builtin: true,
    example: 'aws -> console.aws.amazon.com',
  },
  {
    keys: ['gcp', 'gcloud'],
    name: 'Google Cloud',
    description: 'Google Cloud console.',
    url: 'https://console.cloud.google.com/',
    category: 'dev',
    builtin: true,
    example: 'gcp -> console.cloud.google.com',
  },
  {
    keys: ['vercel'],
    name: 'Vercel',
    description: 'Vercel dashboard.',
    url: 'https://vercel.com/dashboard',
    category: 'dev',
    builtin: true,
    example: 'vercel -> vercel.com/dashboard',
  },
  {
    keys: ['netlify'],
    name: 'Netlify',
    description: 'Netlify dashboard.',
    url: 'https://app.netlify.com/',
    category: 'dev',
    builtin: true,
    example: 'netlify -> app.netlify.com',
  },
  {
    keys: ['cf', 'cloudflare'],
    name: 'Cloudflare',
    description: 'Cloudflare dashboard.',
    url: 'https://dash.cloudflare.com/',
    category: 'dev',
    builtin: true,
    example: 'cf -> dash.cloudflare.com',
  },
  {
    keys: ['kaggle'],
    name: 'Kaggle',
    description: 'Search datasets, notebooks and competitions.',
    url: 'https://www.kaggle.com/',
    searchUrl: 'https://www.kaggle.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'kaggle titanic',
  },
  {
    keys: ['arxiv'],
    name: 'arXiv',
    description: 'Search preprints.',
    url: 'https://arxiv.org/',
    searchUrl: 'https://arxiv.org/search/?searchtype=all&query={q}',
    category: 'dev',
    builtin: true,
    example: 'arxiv speculative decoding',
  },

  // ------------------------------------------------------------ search ----
  {
    keys: ['g', 'google'],
    name: 'Google',
    description: 'Plain Google search.',
    url: 'https://www.google.com/',
    searchUrl: 'https://www.google.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'g best mechanical keyboard',
  },
  {
    keys: ['ddg', 'duckduckgo'],
    name: 'DuckDuckGo',
    description: 'Search DuckDuckGo.',
    url: 'https://duckduckgo.com/',
    searchUrl: 'https://duckduckgo.com/?q={q}',
    category: 'search',
    builtin: true,
    example: 'ddg privacy focused browsers',
  },
  {
    keys: ['yt', 'youtube'],
    name: 'YouTube',
    description: 'Search YouTube, or jump to a channel with @handle.',
    url: 'https://www.youtube.com/',
    handler: 'youtube',
    category: 'search',
    builtin: true,
    example: 'yt lofi beats',
  },
  {
    keys: ['wiki', 'w', 'wikipedia'],
    name: 'Wikipedia',
    description: 'Search English Wikipedia.',
    url: 'https://en.wikipedia.org/',
    searchUrl: 'https://en.wikipedia.org/w/index.php?search={q}',
    category: 'search',
    builtin: true,
    example: 'wiki halting problem',
  },
  {
    keys: ['amz', 'amazon'],
    name: 'Amazon',
    description: 'Search Amazon.',
    url: 'https://www.amazon.com/',
    searchUrl: 'https://www.amazon.com/s?k={q}',
    category: 'search',
    builtin: true,
    example: 'amz usb c hub',
  },
  {
    keys: ['ebay'],
    name: 'eBay',
    description: 'Search eBay listings.',
    url: 'https://www.ebay.com/',
    searchUrl: 'https://www.ebay.com/sch/i.html?_nkw={q}',
    category: 'search',
    builtin: true,
    example: 'ebay thinkpad x1',
  },
  {
    keys: ['gr', 'goodreads'],
    name: 'Goodreads',
    description: 'Search books and reviews.',
    url: 'https://www.goodreads.com/',
    searchUrl: 'https://www.goodreads.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'gr project hail mary',
  },
  {
    keys: ['hn', 'hackernews'],
    name: 'Hacker News',
    description: 'Search Hacker News via Algolia.',
    url: 'https://news.ycombinator.com/',
    searchUrl: 'https://hn.algolia.com/?q={q}',
    category: 'search',
    builtin: true,
    example: 'hn postgres full text search',
  },
  {
    keys: ['wolfram'],
    name: 'WolframAlpha',
    description: 'Compute answers, units and math.',
    url: 'https://www.wolframalpha.com/',
    searchUrl: 'https://www.wolframalpha.com/input?i={q}',
    category: 'search',
    builtin: true,
    example: 'wolfram 42 miles in km',
  },
  {
    keys: ['def', 'dict', 'define'],
    name: 'Merriam-Webster',
    description: 'Look up a word.',
    url: 'https://www.merriam-webster.com/',
    searchUrl: 'https://www.merriam-webster.com/dictionary/{q}',
    handler: 'word',
    category: 'search',
    builtin: true,
    example: 'def defenestrate',
  },
  {
    keys: ['thes', 'thesaurus'],
    name: 'Thesaurus',
    description: 'Find synonyms.',
    url: 'https://www.thesaurus.com/',
    searchUrl: 'https://www.thesaurus.com/browse/{q}',
    handler: 'word',
    category: 'search',
    builtin: true,
    example: 'thes concise',
  },
  {
    keys: ['ud', 'urban'],
    name: 'Urban Dictionary',
    description: 'Slang definitions.',
    url: 'https://www.urbandictionary.com/',
    searchUrl: 'https://www.urbandictionary.com/define.php?term={q}',
    category: 'search',
    builtin: true,
    example: 'ud yeet',
  },

  // ------------------------------------------------------------ social ----
  {
    keys: ['x', 'twitter', 'tw'],
    name: 'X',
    description: 'Search X, formerly Twitter.',
    url: 'https://x.com/',
    searchUrl: 'https://x.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'x from:sama',
  },
  {
    keys: ['li', 'linkedin'],
    name: 'LinkedIn',
    description: 'Search people, jobs and companies.',
    url: 'https://www.linkedin.com/feed/',
    searchUrl: 'https://www.linkedin.com/search/results/all/?keywords={q}',
    category: 'social',
    builtin: true,
    example: 'li software engineer intern',
  },
  {
    keys: ['rd', 'reddit', 'r'],
    name: 'Reddit',
    description: 'Jump to a subreddit or search Reddit.',
    url: 'https://www.reddit.com/',
    handler: 'reddit',
    category: 'social',
    builtin: true,
    example: 'rd r/purdue -> reddit.com/r/purdue',
  },
  {
    keys: ['ig', 'insta', 'instagram'],
    name: 'Instagram',
    description: 'Open a profile by username.',
    url: 'https://www.instagram.com/',
    searchUrl: 'https://www.instagram.com/{q}/',
    handler: 'instagram',
    category: 'social',
    builtin: true,
    example: 'ig nasa -> instagram.com/nasa',
  },
  {
    keys: ['fb', 'facebook'],
    name: 'Facebook',
    description: 'Search Facebook.',
    url: 'https://www.facebook.com/',
    searchUrl: 'https://www.facebook.com/search/top?q={q}',
    category: 'social',
    builtin: true,
    example: 'fb purdue engineering',
  },
  {
    keys: ['bsky', 'bluesky'],
    name: 'Bluesky',
    description: 'Search Bluesky.',
    url: 'https://bsky.app/',
    searchUrl: 'https://bsky.app/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'bsky atproto',
  },
  {
    keys: ['threads'],
    name: 'Threads',
    description: 'Search Threads.',
    url: 'https://www.threads.com/',
    searchUrl: 'https://www.threads.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'threads wwdc',
  },
  {
    keys: ['tt', 'tiktok'],
    name: 'TikTok',
    description: 'Search TikTok.',
    url: 'https://www.tiktok.com/',
    searchUrl: 'https://www.tiktok.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'tt study with me',
  },
  {
    keys: ['pin', 'pinterest'],
    name: 'Pinterest',
    description: 'Search pins.',
    url: 'https://www.pinterest.com/',
    searchUrl: 'https://www.pinterest.com/search/pins/?q={q}',
    category: 'social',
    builtin: true,
    example: 'pin desk setup',
  },
  {
    keys: ['discord', 'dc'],
    name: 'Discord',
    description: 'Open Discord in the browser.',
    url: 'https://discord.com/channels/@me',
    searchUrl: siteSearch('discord.com'),
    category: 'social',
    builtin: true,
    example: 'discord -> discord.com',
  },
  {
    keys: ['wa'],
    name: 'WhatsApp',
    description: 'WhatsApp Web, or start a chat with a phone number.',
    url: 'https://web.whatsapp.com/',
    searchUrl: 'https://wa.me/{q}',
    handler: 'whatsapp',
    category: 'social',
    builtin: true,
    example: 'wa 15551234567',
  },

  // ------------------------------------------------------ productivity ----
  {
    // www.notion.so now 307s to the marketing homepage; app.notion.com is the
    // app shell. Notion exposes no URL-addressable workspace search, so
    // arguments degrade to the same site: search the other workspace tools use.
    keys: ['nt', 'notion'],
    name: 'Notion',
    description: 'Open Notion, or search public Notion pages.',
    url: 'https://app.notion.com/',
    searchUrl: siteSearch('notion.com'),
    category: 'productivity',
    builtin: true,
    example: 'nt meeting notes',
  },
  {
    keys: ['fig', 'figma'],
    name: 'Figma',
    description: 'Open your Figma files.',
    url: 'https://www.figma.com/files',
    searchUrl: siteSearch('figma.com'),
    category: 'productivity',
    builtin: true,
    example: 'fig -> figma.com/files',
  },
  {
    keys: ['lin', 'linear'],
    name: 'Linear',
    description: 'Open Linear.',
    url: 'https://linear.app/',
    searchUrl: siteSearch('linear.app'),
    category: 'productivity',
    builtin: true,
    example: 'lin -> linear.app',
  },
  {
    keys: ['jira'],
    name: 'Jira',
    description: 'Jira home and documentation.',
    url: 'https://www.atlassian.com/software/jira',
    searchUrl: siteSearch('atlassian.com'),
    category: 'productivity',
    builtin: true,
    example: 'jira jql order by',
  },
  {
    keys: ['asana'],
    name: 'Asana',
    description: 'Open Asana.',
    url: 'https://app.asana.com/',
    searchUrl: siteSearch('asana.com'),
    category: 'productivity',
    builtin: true,
    example: 'asana -> app.asana.com',
  },
  {
    keys: ['trello'],
    name: 'Trello',
    description: 'Search your Trello boards and cards.',
    url: 'https://trello.com/',
    searchUrl: 'https://trello.com/search?q={q}',
    category: 'productivity',
    builtin: true,
    example: 'trello sprint board',
  },
  {
    keys: ['canva'],
    name: 'Canva',
    description: 'Open Canva.',
    url: 'https://www.canva.com/',
    searchUrl: siteSearch('canva.com'),
    category: 'productivity',
    builtin: true,
    example: 'canva -> canva.com',
  },
  {
    // Arguments SEARCH. Quick-add lives on `tda` instead: a misread query
    // ("td bank near me") must not create a task, and every other command in
    // the registry is read-only.
    keys: ['todoist', 'td'],
    name: 'Todoist',
    description: 'Open Todoist, or search your tasks.',
    url: 'https://app.todoist.com/app/today',
    searchUrl: 'https://app.todoist.com/app/search/{q}',
    category: 'productivity',
    builtin: true,
    example: 'todoist email advisor',
  },
  {
    keys: ['tda', 'todoistadd'],
    name: 'Todoist quick add',
    description: 'Open the Todoist quick-add composer, prefilled.',
    url: 'https://app.todoist.com/add',
    searchUrl: 'https://app.todoist.com/add?content={q}',
    category: 'productivity',
    builtin: true,
    example: 'tda email advisor tomorrow',
  },
  {
    keys: ['1p', '1password'],
    name: '1Password',
    description: 'Open your 1Password vault.',
    url: 'https://my.1password.com/',
    searchUrl: siteSearch('1password.com'),
    category: 'productivity',
    builtin: true,
    example: '1p -> my.1password.com',
  },
  {
    keys: ['dbx', 'dropbox'],
    name: 'Dropbox',
    description: 'Open Dropbox.',
    url: 'https://www.dropbox.com/home',
    searchUrl: siteSearch('dropbox.com'),
    category: 'productivity',
    builtin: true,
    example: 'dbx -> dropbox.com/home',
  },
  {
    keys: ['airtable'],
    name: 'Airtable',
    description: 'Open Airtable.',
    url: 'https://www.airtable.com/',
    searchUrl: siteSearch('airtable.com'),
    category: 'productivity',
    builtin: true,
    example: 'airtable -> airtable.com',
  },
  {
    keys: ['miro'],
    name: 'Miro',
    description: 'Open your Miro boards.',
    url: 'https://miro.com/app/dashboard/',
    searchUrl: siteSearch('miro.com'),
    category: 'productivity',
    builtin: true,
    example: 'miro -> miro.com',
  },
  {
    keys: ['zoom'],
    name: 'Zoom',
    description: 'Open Zoom, or join a meeting by ID.',
    url: 'https://zoom.us/',
    searchUrl: 'https://zoom.us/j/{q}',
    handler: 'zoom',
    category: 'productivity',
    builtin: true,
    example: 'zoom 1234567890',
  },
  {
    keys: ['overleaf', 'tex'],
    name: 'Overleaf',
    description: 'LaTeX projects in the browser.',
    url: 'https://www.overleaf.com/project',
    searchUrl: siteSearch('overleaf.com'),
    category: 'productivity',
    builtin: true,
    example: 'overleaf bibliography styles',
  },
  {
    keys: ['desmos'],
    name: 'Desmos',
    description: 'Graphing calculator.',
    url: 'https://www.desmos.com/calculator',
    searchUrl: siteSearch('desmos.com'),
    category: 'productivity',
    builtin: true,
    example: 'desmos -> desmos.com/calculator',
  },
  {
    keys: ['ups'],
    name: 'UPS Tracking',
    description: 'Track a UPS shipment.',
    url: 'https://www.ups.com/track',
    searchUrl: 'https://www.ups.com/track?tracknum={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'ups 1Z999AA10123456784',
  },
  {
    keys: ['fedex'],
    name: 'FedEx Tracking',
    description: 'Track a FedEx shipment.',
    url: 'https://www.fedex.com/wtrk/track/',
    searchUrl: 'https://www.fedex.com/wtrk/track/?trknbr={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'fedex 123456789012',
  },
  {
    keys: ['usps'],
    name: 'USPS Tracking',
    description: 'Track a USPS shipment.',
    url: 'https://tools.usps.com/go/TrackConfirmAction',
    searchUrl: 'https://tools.usps.com/go/TrackConfirmAction?tLabels={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'usps 9400111899223197428490',
  },
  {
    keys: ['dhl'],
    name: 'DHL Tracking',
    description: 'Track a DHL shipment.',
    url: 'https://www.dhl.com/global-en/home/tracking.html',
    searchUrl: 'https://www.dhl.com/global-en/home/tracking.html?tracking-id={q}',
    handler: 'tracking',
    category: 'productivity',
    builtin: true,
    example: 'dhl 1234567890',
  },
  {
    keys: ['track', 'pkg'],
    name: 'Track a package',
    description: 'Paste any tracking number; the carrier (UPS, USPS, FedEx or DHL) is read off its shape.',
    // A bare `track` has no carrier to go to, so it lands on the one page that
    // accepts every carrier's number.
    url: 'https://parcelsapp.com/',
    handler: 'track',
    category: 'productivity',
    builtin: true,
    example: 'track 1Z999AA10123456784 -> ups.com',
  },

  // -------------------------------------------------------------- meta ----
  {
    keys: ['bl', 'help', 'bunnylol'],
    name: 'BunnyLol help',
    description: 'Browse and search every shortcut.',
    url: `${OPTIONS_PAGE}#help`,
    handler: 'meta',
    category: 'meta',
    builtin: true,
    example: 'bl -> the full command list',
  },
  {
    keys: ['add', 'new'],
    name: 'New shortcut',
    description: 'Create a shortcut; arguments prefill the form.',
    url: `${OPTIONS_PAGE}#new`,
    handler: 'meta',
    category: 'meta',
    builtin: true,
    example: 'add tix https://example.com/search?q={q}',
  },
  {
    keys: ['set', 'settings', 'opts'],
    name: 'BunnyLol settings',
    description: 'Default engine, GitHub user, interception.',
    url: `${OPTIONS_PAGE}#settings`,
    handler: 'meta',
    category: 'meta',
    builtin: true,
    example: 'set -> the settings page',
  },
];

export const SEARCH_ENGINES: SearchEngine[] = [
  {
    id: 'google',
    label: 'Google',
    host: 'www.google.com',
    urlPrefixPattern: '^https://www\\.google\\.com/search\\?(?:[^#]*&)?q=',
  },
  {
    id: 'bing',
    label: 'Bing',
    host: 'www.bing.com',
    urlPrefixPattern: '^https://www\\.bing\\.com/search\\?(?:[^#]*&)?q=',
  },
  {
    id: 'duckduckgo',
    label: 'DuckDuckGo',
    host: 'duckduckgo.com',
    urlPrefixPattern: '^https://duckduckgo\\.com/\\?(?:[^#]*&)?q=',
  },
];

const SEARCH_ENGINE_HOSTS = new Set(SEARCH_ENGINES.map((engine) => engine.host));

/**
 * True for a template that runs on a search engine: a `site:` degrade for a
 * login-walled destination, not a page on the command's own site.
 */
function isEngineSearch(template: string): boolean {
  try {
    return SEARCH_ENGINE_HOSTS.has(new URL(template).hostname);
  } catch {
    return false;
  }
}

/**
 * Which of a command's two urls to advertise as "where this goes": the search
 * template when there is one, because that is where the keyword goes once it
 * has arguments.
 *
 * Except when a handler owns the arguments AND its template is a plain web
 * search: `bs 12345` opens a course on the Brightspace the row itself points
 * at, and `site:purdue.edu` is only what the words degrade to. Showing that
 * search would hide `url`, the one field a user at another institution has to
 * edit, from the list they would look in for it.
 *
 * It lives beside the registry rather than in the options page because it is a
 * fact about the rows, and because the options page has no test suite.
 */
export function destinationOf(cmd: Command): string {
  const search = cmd.searchUrl;
  if (!search) return cmd.url;
  return cmd.handler && isEngineSearch(search) ? cmd.url : search;
}
