/**
 * Commands removed from the builtin registry, kept verbatim so they can be
 * restored later. Not compiled: `extras/` is outside tsconfig's `include`.
 *
 * To bring one back, paste its object into BUILTIN_COMMANDS in
 * src/lib/commands.ts. If it names a `handler`, that HandlerId and its
 * implementation may also need restoring from git history.
 *
 * Separately, these commands kept their jump but had a Google `site:` search
 * removed, so arguments no longer search their docs:
 *   aws, gcp, vercel, netlify, cf
 */

import type { Command } from '../src/lib/types';

export const REMOVED_COMMANDS: Command[] = [
  {
    // Consumer Copilot has no supported search route: every `?q=` form
    // (including Microsoft's own bing.com/search?showconv=1 entry point) 302s
    // to the bare home page and drops the prompt. Open the app rather than a
    // guessed URL.
    keys: ['copilot', 'msai'],
    name: 'Microsoft Copilot',
    description: 'Open Microsoft Copilot; arguments search the web.',
    url: 'https://copilot.microsoft.com/',
    // The app is a chat SPA with nothing indexed, so a site: search would be as
    // empty as dropping the words: they go to a plain search instead.
    handler: 'unindexed',
    category: 'ai',
    builtin: true,
    example: 'copilot -> copilot.microsoft.com',
  },
  {
    keys: ['hf', 'huggingface'],
    name: 'Hugging Face',
    description: 'Search models, datasets and spaces.',
    url: 'https://huggingface.co/',
    searchUrl: 'https://huggingface.co/search/full-text?q={q}',
    category: 'ai',
    builtin: true,
    example: 'hf whisper large',
  },
  {
    keys: ['bing', 'b'],
    name: 'Bing',
    description: 'Search Bing.',
    url: 'https://www.bing.com/',
    searchUrl: 'https://www.bing.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'bing weather chicago',
  },
  {
    keys: ['brave'],
    name: 'Brave Search',
    description: 'Search with Brave.',
    url: 'https://search.brave.com/',
    searchUrl: 'https://search.brave.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'brave rust vs zig',
  },
  {
    keys: ['kagi'],
    name: 'Kagi',
    description: 'Search with Kagi.',
    url: 'https://kagi.com/',
    searchUrl: 'https://kagi.com/search?q={q}',
    category: 'search',
    builtin: true,
    example: 'kagi sqlite wal mode',
  },
  {
    keys: ['gsite', 'site'],
    name: 'Site search',
    description: 'Google a single site. First word is the domain.',
    url: 'https://www.google.com/',
    handler: 'gsite',
    category: 'search',
    builtin: true,
    example: 'gsite react.dev hooks -> google site:react.dev hooks',
  },
  {
    keys: ['weather', 'wx'],
    name: 'Weather',
    description: 'Weather for a place.',
    url: 'https://www.google.com/search?q=weather',
    searchUrl: 'https://www.google.com/search?q=weather+{q}',
    category: 'search',
    builtin: true,
    example: 'weather west lafayette',
  },
  {
    keys: ['stock', 'ticker'],
    name: 'Yahoo Finance',
    description: 'Quote for a ticker symbol.',
    url: 'https://finance.yahoo.com/',
    searchUrl: 'https://finance.yahoo.com/quote/{q}',
    handler: 'ticker',
    category: 'search',
    builtin: true,
    example: 'stock NVDA',
  },
  {
    keys: ['wayback', 'archive'],
    name: 'Wayback Machine',
    description: 'Latest archived snapshot of a URL.',
    url: 'https://web.archive.org/',
    searchUrl: 'https://web.archive.org/web/2/{q}',
    handler: 'wayback',
    category: 'search',
    builtin: true,
    example: 'wayback nytimes.com',
  },
  {
    keys: ['lh', 'localhost'],
    name: 'localhost',
    description: 'Open a local dev server. Bare invocation uses port 3000.',
    url: 'http://localhost:3000',
    handler: 'localhost',
    category: 'dev',
    builtin: true,
    example: 'lh 8080 -> http://localhost:8080',
  },
  {
    keys: ['so', 'stackoverflow'],
    name: 'Stack Overflow',
    description: 'Search Stack Overflow.',
    url: 'https://stackoverflow.com/',
    searchUrl: 'https://stackoverflow.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'so python asyncio gather exception',
  },
  {
    keys: ['mdn'],
    name: 'MDN Web Docs',
    description: 'Web platform documentation.',
    url: 'https://developer.mozilla.org/',
    searchUrl: 'https://developer.mozilla.org/en-US/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'mdn structuredClone',
  },
  {
    keys: ['caniuse', 'ciu'],
    name: 'Can I use',
    description: 'Browser support tables.',
    url: 'https://caniuse.com/',
    searchUrl: 'https://caniuse.com/?search={q}',
    category: 'dev',
    builtin: true,
    example: 'caniuse container queries',
  },
  {
    keys: ['lc', 'leetcode'],
    name: 'LeetCode',
    description: 'Search LeetCode problems.',
    url: 'https://leetcode.com/problemset/',
    searchUrl: 'https://leetcode.com/problemset/all/?search={q}',
    category: 'dev',
    builtin: true,
    example: 'lc two sum',
  },
  {
    keys: ['pypi'],
    name: 'PyPI',
    description: 'Search Python packages.',
    url: 'https://pypi.org/',
    searchUrl: 'https://pypi.org/search/?q={q}',
    category: 'dev',
    builtin: true,
    example: 'pypi httpx',
  },
  {
    keys: ['pydocs', 'pydoc'],
    name: 'Python Docs',
    description: 'Search the Python 3 standard library docs.',
    url: 'https://docs.python.org/3/',
    searchUrl: 'https://docs.python.org/3/search.html?q={q}',
    category: 'dev',
    builtin: true,
    example: 'pydocs itertools groupby',
  },
  {
    keys: ['crates'],
    name: 'crates.io',
    description: 'Search Rust crates.',
    url: 'https://crates.io/',
    searchUrl: 'https://crates.io/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'crates serde',
  },
  {
    keys: ['docsrs'],
    name: 'docs.rs',
    description: 'Rust crate API documentation.',
    url: 'https://docs.rs/',
    searchUrl: 'https://docs.rs/releases/search?query={q}',
    category: 'dev',
    builtin: true,
    example: 'docsrs tokio',
  },
  {
    keys: ['golang', 'gopkg'],
    name: 'pkg.go.dev',
    description: 'Search Go packages.',
    url: 'https://pkg.go.dev/',
    searchUrl: 'https://pkg.go.dev/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'golang errgroup',
  },
  {
    keys: ['rubygems'],
    name: 'RubyGems',
    description: 'Search Ruby gems.',
    url: 'https://rubygems.org/',
    searchUrl: 'https://rubygems.org/search?query={q}',
    category: 'dev',
    builtin: true,
    example: 'rubygems rails',
  },
  {
    keys: ['packagist', 'composer'],
    name: 'Packagist',
    description: 'Search PHP packages.',
    url: 'https://packagist.org/',
    searchUrl: 'https://packagist.org/?query={q}',
    category: 'dev',
    builtin: true,
    example: 'packagist guzzle',
  },
  {
    keys: ['nuget'],
    name: 'NuGet',
    description: 'Search .NET packages.',
    url: 'https://www.nuget.org/',
    searchUrl: 'https://www.nuget.org/packages?q={q}',
    category: 'dev',
    builtin: true,
    example: 'nuget newtonsoft.json',
  },
  {
    keys: ['mvn', 'maven'],
    name: 'Maven Central',
    description: 'Search Java artifacts.',
    url: 'https://mvnrepository.com/',
    searchUrl: 'https://mvnrepository.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'mvn jackson databind',
  },
  {
    keys: ['dockerhub', 'docker'],
    name: 'Docker Hub',
    description: 'Search container images.',
    url: 'https://hub.docker.com/',
    searchUrl: 'https://hub.docker.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'docker postgres',
  },
  {
    keys: ['gitlab', 'gl'],
    name: 'GitLab',
    description: 'Search GitLab projects.',
    url: 'https://gitlab.com/',
    // gitlab.com/search requires auth and bounces signed-out users to sign-in;
    // /explore/projects is the public equivalent.
    searchUrl: 'https://gitlab.com/explore/projects?name={q}',
    category: 'dev',
    builtin: true,
    example: 'gitlab gitlab-runner',
  },
  {
    keys: ['bitbucket', 'bb'],
    name: 'Bitbucket',
    description: 'Bitbucket workspaces and repos.',
    url: 'https://bitbucket.org/',
    searchUrl: siteSearch('bitbucket.org'),
    category: 'dev',
    builtin: true,
    example: 'bitbucket -> bitbucket.org',
  },
  {
    keys: ['sourcegraph', 'sg'],
    name: 'Sourcegraph',
    description: 'Cross-repository code search.',
    url: 'https://sourcegraph.com/',
    searchUrl: 'https://sourcegraph.com/search?q={q}',
    category: 'dev',
    builtin: true,
    example: 'sg lang:go http.HandlerFunc',
  },
  {
    keys: ['devdocs', 'dd'],
    name: 'DevDocs',
    description: 'Unified API documentation browser.',
    url: 'https://devdocs.io/',
    searchUrl: 'https://devdocs.io/#q={q}',
    category: 'dev',
    builtin: true,
    example: 'dd array.prototype.flatmap',
  },
  {
    keys: ['ts', 'typescript'],
    name: 'TypeScript',
    description: 'TypeScript handbook and docs.',
    url: 'https://www.typescriptlang.org/',
    searchUrl: siteSearch('typescriptlang.org'),
    category: 'dev',
    builtin: true,
    example: 'ts satisfies operator',
  },
  {
    keys: ['react'],
    name: 'React',
    description: 'React documentation.',
    url: 'https://react.dev/',
    searchUrl: siteSearch('react.dev'),
    category: 'dev',
    builtin: true,
    example: 'react useSyncExternalStore',
  },
  {
    keys: ['node', 'nodedocs'],
    name: 'Node.js Docs',
    description: 'Node.js API documentation.',
    url: 'https://nodejs.org/api/',
    searchUrl: siteSearch('nodejs.org'),
    category: 'dev',
    builtin: true,
    example: 'node fs promises readFile',
  },
  {
    keys: ['bundlephobia', 'bphobia'],
    name: 'Bundlephobia',
    description: 'Size cost of an npm package.',
    url: 'https://bundlephobia.com/',
    searchUrl: 'https://bundlephobia.com/package/{q}',
    handler: 'pkg',
    category: 'dev',
    builtin: true,
    example: 'bundlephobia lodash',
  },
  {
    // Package pages intermittently 500 upstream (e.g. /react) while others load;
    // the URL shape is correct, so the command stays as-is.
    keys: ['npmtrends'],
    name: 'npm trends',
    description: 'Compare npm package downloads.',
    url: 'https://npmtrends.com/',
    searchUrl: 'https://npmtrends.com/{q}',
    handler: 'pkg',
    category: 'dev',
    builtin: true,
    example: 'npmtrends vite-vs-webpack',
  },
  {
    keys: ['codepen'],
    name: 'CodePen',
    description: 'Search pens.',
    url: 'https://codepen.io/',
    searchUrl: 'https://codepen.io/search/pens?q={q}',
    category: 'dev',
    builtin: true,
    example: 'codepen css grid gallery',
  },
  {
    keys: ['vscode', 'vsx'],
    name: 'VS Code',
    description: 'VS Code site; arguments search the extension marketplace.',
    url: 'https://code.visualstudio.com/',
    searchUrl: 'https://marketplace.visualstudio.com/search?target=VSCode&term={q}',
    category: 'dev',
    builtin: true,
    example: 'vsx eslint',
  },
  {
    keys: ['gnews', 'news'],
    name: 'Google News',
    description: 'Search the news.',
    url: 'https://news.google.com/',
    searchUrl: 'https://news.google.com/search?q={q}',
    category: 'google',
    builtin: true,
    example: 'news semiconductor tariffs',
  },
  {
    keys: ['gimg', 'img', 'images'],
    name: 'Google Images',
    description: 'Google image search.',
    url: 'https://images.google.com/',
    searchUrl: 'https://www.google.com/search?tbm=isch&q={q}',
    category: 'google',
    builtin: true,
    example: 'img purdue bell tower',
  },
  {
    keys: ['gvid', 'videos'],
    name: 'Google Video',
    description: 'Google video search.',
    url: 'https://www.google.com/search?tbm=vid',
    searchUrl: 'https://www.google.com/search?tbm=vid&q={q}',
    category: 'google',
    builtin: true,
    example: 'gvid rust lifetimes talk',
  },
  {
    keys: ['gbooks', 'books'],
    name: 'Google Books',
    description: 'Search books.',
    url: 'https://books.google.com/',
    searchUrl: 'https://www.google.com/search?tbm=bks&q={q}',
    category: 'google',
    builtin: true,
    example: 'gbooks godel escher bach',
  },
  {
    keys: ['gflights', 'flights'],
    name: 'Google Flights',
    description: 'Search flights.',
    url: 'https://www.google.com/travel/flights',
    searchUrl: 'https://www.google.com/travel/flights?q={q}',
    category: 'google',
    builtin: true,
    example: 'gflights ind to sfo friday',
  },
  {
    keys: ['gtrends', 'trends'],
    name: 'Google Trends',
    description: 'Explore search interest over time.',
    url: 'https://trends.google.com/trends/',
    searchUrl: 'https://trends.google.com/trends/explore?q={q}',
    category: 'google',
    builtin: true,
    example: 'gtrends electric vehicles',
  },
  {
    keys: ['gplay', 'play'],
    name: 'Google Play',
    description: 'Search the Play Store.',
    url: 'https://play.google.com/store',
    searchUrl: 'https://play.google.com/store/search?q={q}',
    category: 'google',
    builtin: true,
    example: 'gplay duolingo',
  },
  {
    keys: ['sharepoint', 'sp'],
    name: 'SharePoint',
    description: 'SharePoint start page, or search your sites.',
    url: 'https://m365.cloud.microsoft/launch/sharepoint',
    searchUrl: 'https://m365.cloud.microsoft/search?q={q}',
    category: 'microsoft',
    builtin: true,
    example: 'sharepoint team site',
  },
  {
    keys: ['azure', 'az'],
    name: 'Azure Portal',
    description: 'Azure portal; arguments search Microsoft Learn.',
    url: 'https://portal.azure.com/',
    searchUrl: 'https://learn.microsoft.com/en-us/search/?terms={q}',
    category: 'microsoft',
    builtin: true,
    example: 'az blob storage lifecycle',
  },
  {
    keys: ['mslearn', 'learn'],
    name: 'Microsoft Learn',
    description: 'Microsoft technical documentation.',
    url: 'https://learn.microsoft.com/',
    searchUrl: 'https://learn.microsoft.com/en-us/search/?terms={q}',
    category: 'microsoft',
    builtin: true,
    example: 'mslearn graph api permissions',
  },
  {
    // Gradescope's own login page; "School Credentials" is the Purdue SAML SSO
    // path. Purdue's former idp/gradescope1 entry point no longer exists.
    keys: ['gss', 'gradescopesso'],
    name: 'Gradescope (Purdue login)',
    description: 'Sign in to Gradescope with Purdue school credentials.',
    url: 'https://www.gradescope.com/login',
    searchUrl: siteSearch('gradescope.com'),
    category: 'purdue',
    builtin: true,
    example: 'gss -> Gradescope login (School Credentials)',
  },
  {
    keys: ['purdue', 'pu'],
    name: 'Purdue University',
    description: 'purdue.edu, or search the Purdue site.',
    url: 'https://www.purdue.edu/',
    searchUrl: siteSearch('purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'purdue academic integrity policy',
  },
  {
    keys: ['boilerconnect', 'bcon'],
    name: 'BoilerConnect',
    description: 'Advising appointments and student success.',
    url: 'https://purdue.campus.eab.com/',
    searchUrl: siteSearch('purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'boilerconnect -> advising appointments',
  },
  {
    keys: ['courseinsights', 'ci'],
    name: 'Purdue Course Insights',
    description: 'Course grade distributions; arguments search the web.',
    // Login-walled SPA: a site: fallback would send arguments nowhere useful, so
    // they go to a plain search. A bare invocation opens the app.
    url: 'https://sswis.mypurdue.purdue.edu/CourseInsights/',
    handler: 'unindexed',
    category: 'purdue',
    builtin: true,
    example: 'ci -> Course Insights',
  },
  {
    keys: ['catalog', 'pcat', 'courses'],
    name: 'Purdue Course Catalog',
    description: 'Official course descriptions and requirements.',
    url: 'https://catalog.purdue.edu/',
    searchUrl: siteSearch('catalog.purdue.edu'),
    category: 'purdue',
    builtin: true,
    example: 'catalog ma 26100',
  },
  {
    keys: ['citybus', 'bus'],
    name: 'CityBus',
    description: 'Greater Lafayette CityBus routes and tracker.',
    url: 'https://www.in.gov/citybuslafayette/',
    searchUrl: siteSearch('in.gov/citybuslafayette'),
    category: 'purdue',
    builtin: true,
    example: 'citybus route 4',
  },
  {
    keys: ['purduesports', 'boilers'],
    name: 'Purdue Athletics',
    description: 'Schedules, scores and tickets.',
    url: 'https://purduesports.com/',
    searchUrl: siteSearch('purduesports.com'),
    category: 'purdue',
    builtin: true,
    example: 'boilers basketball schedule',
  },
  {
    keys: ['piazza'],
    name: 'Piazza',
    description: 'Course Q&A boards.',
    url: 'https://piazza.com/',
    searchUrl: siteSearch('piazza.com'),
    category: 'purdue',
    builtin: true,
    example: 'piazza -> piazza.com',
  },
  {
    keys: ['quora'],
    name: 'Quora',
    description: 'Search questions and answers.',
    url: 'https://www.quora.com/',
    searchUrl: 'https://www.quora.com/search?q={q}',
    category: 'social',
    builtin: true,
    example: 'quora how do jet engines work',
  },
  {
    keys: ['slack', 'slk'],
    name: 'Slack',
    description: 'Open Slack in the browser.',
    url: 'https://app.slack.com/client',
    searchUrl: siteSearch('slack.com'),
    category: 'social',
    builtin: true,
    example: 'slack -> app.slack.com',
  },
  {
    keys: ['spot', 'spotify'],
    name: 'Spotify',
    description: 'Search Spotify.',
    url: 'https://open.spotify.com/',
    searchUrl: 'https://open.spotify.com/search/{q}',
    category: 'media',
    builtin: true,
    example: 'spot bonobo',
  },
  {
    keys: ['ytm', 'ytmusic'],
    name: 'YouTube Music',
    description: 'Search YouTube Music.',
    url: 'https://music.youtube.com/',
    searchUrl: 'https://music.youtube.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'ytm radiohead',
  },
  {
    keys: ['sc', 'soundcloud'],
    name: 'SoundCloud',
    description: 'Search SoundCloud.',
    url: 'https://soundcloud.com/',
    searchUrl: 'https://soundcloud.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'sc dj sets',
  },
  {
    keys: ['bandcamp'],
    name: 'Bandcamp',
    description: 'Search artists and albums.',
    url: 'https://bandcamp.com/',
    searchUrl: 'https://bandcamp.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'bandcamp khruangbin',
  },
  {
    keys: ['genius'],
    name: 'Genius',
    description: 'Search song lyrics.',
    url: 'https://genius.com/',
    searchUrl: 'https://genius.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'genius pyramids',
  },
  {
    keys: ['nf', 'netflix'],
    name: 'Netflix',
    description: 'Search Netflix.',
    url: 'https://www.netflix.com/browse',
    searchUrl: 'https://www.netflix.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'nf arcane',
  },
  {
    keys: ['hulu'],
    name: 'Hulu',
    description: 'Search Hulu.',
    url: 'https://www.hulu.com/hub/home',
    searchUrl: 'https://www.hulu.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'hulu the bear',
  },
  {
    keys: ['primevideo', 'pv'],
    name: 'Prime Video',
    description: 'Open Prime Video.',
    url: 'https://www.primevideo.com/',
    searchUrl: siteSearch('primevideo.com'),
    category: 'media',
    builtin: true,
    example: 'primevideo -> primevideo.com',
  },
  {
    keys: ['disney', 'dplus'],
    name: 'Disney+',
    description: 'Open Disney+.',
    url: 'https://www.disneyplus.com/',
    searchUrl: siteSearch('disneyplus.com'),
    category: 'media',
    builtin: true,
    example: 'disney -> disneyplus.com',
  },
  {
    keys: ['twitch'],
    name: 'Twitch',
    description: 'Search Twitch channels and categories.',
    url: 'https://www.twitch.tv/',
    searchUrl: 'https://www.twitch.tv/search?term={q}',
    category: 'media',
    builtin: true,
    example: 'twitch speedrun',
  },
  {
    keys: ['imdb'],
    name: 'IMDb',
    description: 'Search films, shows and people.',
    url: 'https://www.imdb.com/',
    searchUrl: 'https://www.imdb.com/find/?q={q}',
    category: 'media',
    builtin: true,
    example: 'imdb dune part two',
  },
  {
    keys: ['rt', 'rottentomatoes'],
    name: 'Rotten Tomatoes',
    description: 'Search reviews and scores.',
    url: 'https://www.rottentomatoes.com/',
    searchUrl: 'https://www.rottentomatoes.com/search?search={q}',
    category: 'media',
    builtin: true,
    example: 'rt the batman',
  },
  {
    keys: ['lb', 'letterboxd'],
    name: 'Letterboxd',
    description: 'Search films on Letterboxd.',
    url: 'https://letterboxd.com/',
    searchUrl: 'https://letterboxd.com/search/{q}/',
    category: 'media',
    builtin: true,
    example: 'lb parasite',
  },
  {
    keys: ['gr', 'goodreads'],
    name: 'Goodreads',
    description: 'Search books and reviews.',
    url: 'https://www.goodreads.com/',
    searchUrl: 'https://www.goodreads.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'gr project hail mary',
  },
  {
    keys: ['mal', 'anime'],
    name: 'MyAnimeList',
    description: 'Search anime and manga.',
    url: 'https://myanimelist.net/',
    searchUrl: 'https://myanimelist.net/search/all?q={q}',
    category: 'media',
    builtin: true,
    example: 'mal frieren',
  },
  {
    keys: ['steam'],
    name: 'Steam',
    description: 'Search the Steam store.',
    url: 'https://store.steampowered.com/',
    searchUrl: 'https://store.steampowered.com/search/?term={q}',
    category: 'media',
    builtin: true,
    example: 'steam factorio',
  },
  {
    keys: ['vimeo'],
    name: 'Vimeo',
    description: 'Search Vimeo.',
    url: 'https://vimeo.com/',
    searchUrl: 'https://vimeo.com/search?q={q}',
    category: 'media',
    builtin: true,
    example: 'vimeo short film',
  },
  {
    keys: ['tg', 'telegram'],
    name: 'Telegram',
    description: 'Telegram Web, or open a @username.',
    url: 'https://web.telegram.org/',
    searchUrl: 'https://t.me/{q}',
    handler: 'telegram',
    category: 'social',
    builtin: true,
    example: 'tg durov',
  },
  {
    keys: ['gtrans', 'translate', 'tr'],
    name: 'Google Translate',
    description: 'Translate text into English (auto-detect source).',
    url: 'https://translate.google.com/',
    searchUrl: 'https://translate.google.com/?sl=auto&tl=en&op=translate&text={q}',
    category: 'google',
    builtin: true,
    example: 'tr wo ist der bahnhof',
  },
  {
    keys: ['gkeep', 'keep'],
    name: 'Google Keep',
    description: 'Open Keep or search your notes.',
    url: 'https://keep.google.com/',
    searchUrl: 'https://keep.google.com/#search/text={q}',
    category: 'google',
    builtin: true,
    example: 'gkeep groceries',
  },
  {
    keys: ['gphotos', 'photos'],
    name: 'Google Photos',
    description: 'Open Photos or search your library.',
    url: 'https://photos.google.com/',
    searchUrl: 'https://photos.google.com/search/{q}',
    category: 'google',
    builtin: true,
    example: 'gphotos graduation',
  },
  {
    keys: ['gscholar', 'sch', 'scholar'],
    name: 'Google Scholar',
    description: 'Search academic papers.',
    url: 'https://scholar.google.com/',
    searchUrl: 'https://scholar.google.com/scholar?q={q}',
    category: 'google',
    builtin: true,
    example: 'sch attention is all you need',
  },
  {
    keys: ['gcontacts', 'contacts'],
    name: 'Google Contacts',
    description: 'Open Contacts or search people.',
    url: 'https://contacts.google.com/',
    searchUrl: 'https://contacts.google.com/search/{q}',
    category: 'google',
    builtin: true,
    example: 'gcontacts jordan',
  },
];
